root = "."
tmp_dir = "tmp"

[build]
  entrypoint = ["./tmp/main"]
  cmd = "go build -o ./tmp/main main.go"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "test", "scripts", "uploads", ".git", ".idea", ".vscode", "migrations"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  go_bin = "go"
  include_dir = ["internal", "pkg", "trigger"]
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "env", "trigger"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = true

