// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Candidate struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Avatar          pgtype.Text        `json:"avatar"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	ExperienceYears int32              `json:"experience_years"`
	Education       string             `json:"education"`
	AppliedJobID    pgtype.UUID        `json:"applied_job_id"`
	Channel         string             `json:"channel"`
	ResumeUrl       string             `json:"resume_url"`
	Status          string             `json:"status"`
	Note            pgtype.Text        `json:"note"`
	AppliedAt       pgtype.Timestamptz `json:"applied_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CandidateStatus struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Type      string             `json:"type"`
	SortOrder int32              `json:"sort_order"`
	Color     string             `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Employee struct {
	ID         pgtype.UUID `json:"id"`
	FirstName  string      `json:"first_name"`
	LastName   string      `json:"last_name"`
	Email      string      `json:"email"`
	Phone      string      `json:"phone"`
	Department string      `json:"department"`
	Position   string      `json:"position"`
	// Active, OnLeave, Resigned, Terminated
	Status string `json:"status"`
	// FullTime, PartTime, Contract, Intern
	EmploymentType string             `json:"employment_type"`
	JoinDate       pgtype.Timestamptz `json:"join_date"`
	ManagerID      pgtype.UUID        `json:"manager_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Interview struct {
	ID            pgtype.UUID        `json:"id"`
	CandidateID   pgtype.UUID        `json:"candidate_id"`
	InterviewerID pgtype.UUID        `json:"interviewer_id"`
	JobID         pgtype.UUID        `json:"job_id"`
	ScheduledTime pgtype.Timestamptz `json:"scheduled_time"`
	Status        string             `json:"status"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Job struct {
	ID             pgtype.UUID        `json:"id"`
	Title          string             `json:"title"`
	Department     string             `json:"department"`
	HeadCount      int32              `json:"head_count"`
	OpenDate       pgtype.Timestamptz `json:"open_date"`
	JobDescription string             `json:"job_description"`
	Note           pgtype.Text        `json:"note"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type RecruitmentRole struct {
	EmployeeID pgtype.UUID        `json:"employee_id"`
	RoleType   string             `json:"role_type"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Avatar       pgtype.Text        `json:"avatar"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	IsAdmin      bool               `json:"is_admin"`
}
