// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Candidate struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Avatar          pgtype.Text        `json:"avatar"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	ExperienceYears int32              `json:"experience_years"`
	Education       string             `json:"education"`
	AppliedJobID    pgtype.UUID        `json:"applied_job_id"`
	Channel         string             `json:"channel"`
	ResumeUrl       string             `json:"resume_url"`
	Status          string             `json:"status"`
	AppliedAt       pgtype.Timestamptz `json:"applied_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ReviewerID      pgtype.UUID        `json:"reviewer_id"`
	ReviewStatus    pgtype.Text        `json:"review_status"`
}

type CandidateComment struct {
	ID          pgtype.UUID        `json:"id"`
	CandidateID pgtype.UUID        `json:"candidate_id"`
	AuthorID    pgtype.UUID        `json:"author_id"`
	Content     string             `json:"content"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CandidateReviewer struct {
	ID           pgtype.UUID        `json:"id"`
	CandidateID  pgtype.UUID        `json:"candidate_id"`
	ReviewerID   pgtype.UUID        `json:"reviewer_id"`
	AssignedAt   pgtype.Timestamp   `json:"assigned_at"`
	RemovedAt    pgtype.Timestamp   `json:"removed_at"`
	CreatedAt    pgtype.Timestamp   `json:"created_at"`
	ReviewStatus string             `json:"review_status"`
	ReviewedAt   pgtype.Timestamptz `json:"reviewed_at"`
}

type CandidateStatus struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Type      string             `json:"type"`
	SortOrder int32              `json:"sort_order"`
	Color     string             `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	IsDeleted bool               `json:"is_deleted"`
}

type Employee struct {
	ID         pgtype.UUID `json:"id"`
	FirstName  string      `json:"first_name"`
	LastName   string      `json:"last_name"`
	Email      string      `json:"email"`
	Phone      string      `json:"phone"`
	Department string      `json:"department"`
	Position   string      `json:"position"`
	// Active, OnLeave, Resigned, Terminated
	Status string `json:"status"`
	// FullTime, PartTime, Contract, Intern
	EmploymentType string             `json:"employment_type"`
	JoinDate       pgtype.Timestamptz `json:"join_date"`
	ManagerID      pgtype.UUID        `json:"manager_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	// HR, EMPLOYEE
	EmployeeType string `json:"employee_type"`
}

type Interview struct {
	ID                  pgtype.UUID        `json:"id"`
	CandidateID         pgtype.UUID        `json:"candidate_id"`
	InterviewerID       pgtype.UUID        `json:"interviewer_id"`
	JobID               pgtype.UUID        `json:"job_id"`
	ScheduledTime       pgtype.Timestamptz `json:"scheduled_time"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ScheduledEndTime    pgtype.Timestamptz `json:"scheduled_end_time"`
	CandidateStatusID   pgtype.UUID        `json:"candidate_status_id"`
	SnapshotStatusKey   string             `json:"snapshot_status_key"`
	SnapshotStatusLabel string             `json:"snapshot_status_label"`
}

type Job struct {
	ID             pgtype.UUID        `json:"id"`
	Title          string             `json:"title"`
	Department     string             `json:"department"`
	HeadCount      int32              `json:"head_count"`
	OpenDate       pgtype.Timestamptz `json:"open_date"`
	JobDescription string             `json:"job_description"`
	Note           pgtype.Text        `json:"note"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Notification struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	EventType   string             `json:"event_type"`
	SubjectType string             `json:"subject_type"`
	SubjectID   pgtype.UUID        `json:"subject_id"`
	Context     []byte             `json:"context"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RecruitmentRole struct {
	EmployeeID pgtype.UUID        `json:"employee_id"`
	RoleType   string             `json:"role_type"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	DeviceInfo   []byte             `json:"device_info"`
	IpAddress    pgtype.Text        `json:"ip_address"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	IsActive     pgtype.Bool        `json:"is_active"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Avatar       pgtype.Text        `json:"avatar"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	IsAdmin      bool               `json:"is_admin"`
}
