// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Candidate struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Avatar          pgtype.Text        `json:"avatar"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	ExperienceYears int32              `json:"experience_years"`
	Education       string             `json:"education"`
	AppliedJobID    pgtype.UUID        `json:"applied_job_id"`
	Channel         string             `json:"channel"`
	ResumeUrl       string             `json:"resume_url"`
	Status          string             `json:"status"`
	Note            pgtype.Text        `json:"note"`
	AppliedAt       pgtype.Timestamptz `json:"applied_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Job struct {
	ID             pgtype.UUID        `json:"id"`
	Title          string             `json:"title"`
	Department     string             `json:"department"`
	HeadCount      int32              `json:"head_count"`
	OpenDate       pgtype.Timestamptz `json:"open_date"`
	JobDescription string             `json:"job_description"`
	Note           pgtype.Text        `json:"note"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Avatar       pgtype.Text        `json:"avatar"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
