// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    user_id,
    event_type,
    subject_type,
    subject_id,
    context
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, event_type, subject_type, subject_id, context, read_at, created_at
`

type CreateNotificationParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	EventType   string      `json:"event_type"`
	SubjectType string      `json:"subject_type"`
	SubjectID   pgtype.UUID `json:"subject_id"`
	Context     []byte      `json:"context"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.EventType,
		arg.SubjectType,
		arg.SubjectID,
		arg.Context,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventType,
		&i.SubjectType,
		&i.SubjectID,
		&i.Context,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications
WHERE id = $1 AND user_id = $2
`

type DeleteNotificationParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error {
	_, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.UserID)
	return err
}

const deleteNotificationsBySubjectAndType = `-- name: DeleteNotificationsBySubjectAndType :exec
DELETE FROM notifications
WHERE user_id = $1
  AND subject_type = $2
  AND subject_id = $3
  AND event_type = $4
`

type DeleteNotificationsBySubjectAndTypeParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	SubjectType string      `json:"subject_type"`
	SubjectID   pgtype.UUID `json:"subject_id"`
	EventType   string      `json:"event_type"`
}

func (q *Queries) DeleteNotificationsBySubjectAndType(ctx context.Context, arg DeleteNotificationsBySubjectAndTypeParams) error {
	_, err := q.db.Exec(ctx, deleteNotificationsBySubjectAndType,
		arg.UserID,
		arg.SubjectType,
		arg.SubjectID,
		arg.EventType,
	)
	return err
}

const deleteNotificationsBySubjectIDAndEventType = `-- name: DeleteNotificationsBySubjectIDAndEventType :exec
DELETE FROM notifications
WHERE subject_id = $1 AND event_type = $2
`

type DeleteNotificationsBySubjectIDAndEventTypeParams struct {
	SubjectID pgtype.UUID `json:"subject_id"`
	EventType string      `json:"event_type"`
}

func (q *Queries) DeleteNotificationsBySubjectIDAndEventType(ctx context.Context, arg DeleteNotificationsBySubjectIDAndEventTypeParams) error {
	_, err := q.db.Exec(ctx, deleteNotificationsBySubjectIDAndEventType, arg.SubjectID, arg.EventType)
	return err
}

const getNotificationsByUserId = `-- name: GetNotificationsByUserId :many
SELECT id, user_id, event_type, subject_type, subject_id, context, read_at, created_at
FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetNotificationsByUserIdParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) GetNotificationsByUserId(ctx context.Context, arg GetNotificationsByUserIdParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getNotificationsByUserId, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventType,
			&i.SubjectType,
			&i.SubjectID,
			&i.Context,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadNotificationCount = `-- name: GetUnreadNotificationCount :one
SELECT COUNT(*)
FROM notifications
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) GetUnreadNotificationCount(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadNotificationCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE notifications
SET read_at = CURRENT_TIMESTAMP
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsAsRead, userID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :exec
UPDATE notifications
SET read_at = COALESCE(read_at, CURRENT_TIMESTAMP)
WHERE id = $1 AND user_id = $2
`

type MarkNotificationAsReadParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationAsRead, arg.ID, arg.UserID)
	return err
}
