// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignHRRole = `-- name: AssignHRRole :exec

UPDATE employees
SET employee_type = 'HR',
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

// HR Role queries
func (q *Queries) AssignHRRole(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, assignHRRole, id)
	return err
}

const assignInterviewerRole = `-- name: AssignInterviewerRole :exec
INSERT INTO recruitment_roles (employee_id, role_type)
VALUES ($1, 'INTERVIEWER')
ON CONFLICT (employee_id, role_type) DO NOTHING
`

func (q *Queries) AssignInterviewerRole(ctx context.Context, employeeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, assignInterviewerRole, employeeID)
	return err
}

const assignRecruiterRole = `-- name: AssignRecruiterRole :exec
INSERT INTO recruitment_roles (employee_id, role_type)
VALUES ($1, 'RECRUITER')
ON CONFLICT (employee_id, role_type) DO NOTHING
`

func (q *Queries) AssignRecruiterRole(ctx context.Context, employeeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, assignRecruiterRole, employeeID)
	return err
}

const assignReviewer = `-- name: AssignReviewer :one
UPDATE candidates c
SET reviewer_id = $2,
    review_status = 'pending',
    updated_at = CURRENT_TIMESTAMP
FROM jobs j
LEFT JOIN employees e ON $2 = e.id
WHERE c.id = $1 AND c.applied_job_id = j.id
RETURNING 
    c.id, c.name, c.avatar, c.email, c.phone, c.experience_years, c.education, c.applied_job_id, c.channel, c.resume_url, c.status, c.applied_at, c.created_at, c.updated_at, c.reviewer_id, c.review_status, 
    j.title as applied_job_title,
    e.first_name as reviewer_first_name,
    e.last_name as reviewer_last_name
`

type AssignReviewerParams struct {
	ID         pgtype.UUID `json:"id"`
	ReviewerID pgtype.UUID `json:"reviewer_id"`
}

type AssignReviewerRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Avatar            pgtype.Text        `json:"avatar"`
	Email             string             `json:"email"`
	Phone             string             `json:"phone"`
	ExperienceYears   int32              `json:"experience_years"`
	Education         string             `json:"education"`
	AppliedJobID      pgtype.UUID        `json:"applied_job_id"`
	Channel           string             `json:"channel"`
	ResumeUrl         string             `json:"resume_url"`
	Status            string             `json:"status"`
	AppliedAt         pgtype.Timestamptz `json:"applied_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ReviewerID        pgtype.UUID        `json:"reviewer_id"`
	ReviewStatus      pgtype.Text        `json:"review_status"`
	AppliedJobTitle   string             `json:"applied_job_title"`
	ReviewerFirstName string             `json:"reviewer_first_name"`
	ReviewerLastName  string             `json:"reviewer_last_name"`
}

func (q *Queries) AssignReviewer(ctx context.Context, arg AssignReviewerParams) (AssignReviewerRow, error) {
	row := q.db.QueryRow(ctx, assignReviewer, arg.ID, arg.ReviewerID)
	var i AssignReviewerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.ExperienceYears,
		&i.Education,
		&i.AppliedJobID,
		&i.Channel,
		&i.ResumeUrl,
		&i.Status,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewerID,
		&i.ReviewStatus,
		&i.AppliedJobTitle,
		&i.ReviewerFirstName,
		&i.ReviewerLastName,
	)
	return i, err
}

const checkInterviewerRole = `-- name: CheckInterviewerRole :one
SELECT employee_id FROM recruitment_roles WHERE employee_id = $1 AND role_type = 'INTERVIEWER' LIMIT 1
`

func (q *Queries) CheckInterviewerRole(ctx context.Context, employeeID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, checkInterviewerRole, employeeID)
	var employee_id pgtype.UUID
	err := row.Scan(&employee_id)
	return employee_id, err
}

const checkIsAdmin = `-- name: CheckIsAdmin :one

SELECT is_admin FROM users WHERE id = $1 LIMIT 1
`

// Recruitment Role queries
func (q *Queries) CheckIsAdmin(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkIsAdmin, id)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const checkIsHR = `-- name: CheckIsHR :one
SELECT employee_type = 'HR' as is_hr FROM employees WHERE id = $1 LIMIT 1
`

func (q *Queries) CheckIsHR(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkIsHR, id)
	var is_hr bool
	err := row.Scan(&is_hr)
	return is_hr, err
}

const checkRecruiterOrAdmin = `-- name: CheckRecruiterOrAdmin :one
SELECT EXISTS(
    SELECT 1 FROM users u WHERE u.id = $1 AND u.is_admin = TRUE
) OR EXISTS(
    SELECT 1 FROM recruitment_roles rr
    JOIN employees e ON rr.employee_id = e.id
    WHERE e.user_id = $1 AND rr.role_type = 'RECRUITER'
)
`

func (q *Queries) CheckRecruiterOrAdmin(ctx context.Context, id pgtype.UUID) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, checkRecruiterOrAdmin, id)
	var column_1 pgtype.Bool
	err := row.Scan(&column_1)
	return column_1, err
}

const checkRecruiterRole = `-- name: CheckRecruiterRole :one
SELECT employee_id
FROM recruitment_roles
WHERE employee_id = $1 AND role_type = 'RECRUITER'
LIMIT 1
`

func (q *Queries) CheckRecruiterRole(ctx context.Context, employeeID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, checkRecruiterRole, employeeID)
	var employee_id pgtype.UUID
	err := row.Scan(&employee_id)
	return employee_id, err
}

const clearCandidateReviewer = `-- name: ClearCandidateReviewer :exec
UPDATE candidates
SET reviewer_id = NULL,
    review_status = NULL,
    review_note = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) ClearCandidateReviewer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearCandidateReviewer, id)
	return err
}

const countCandidateReviewerAssignments = `-- name: CountCandidateReviewerAssignments :one

SELECT COUNT(*)
FROM candidate_reviewers
WHERE reviewer_id = $1 AND removed_at IS NULL
`

// Candidate Reviewer queries
func (q *Queries) CountCandidateReviewerAssignments(ctx context.Context, reviewerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCandidateReviewerAssignments, reviewerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCandidates = `-- name: CountCandidates :one
SELECT COUNT(*)
FROM candidates c
WHERE ($1::uuid IS NULL OR c.applied_job_id = $1)
  AND ($2::uuid IS NULL OR c.reviewer_id = $2)
  AND ($3::text IS NULL OR c.review_status = $3)
  AND ($4::text IS NULL OR c.status = $4)
  AND ($5::text IS NULL OR 
       c.name ILIKE '%' || $5::text || '%' OR 
       c.email ILIKE '%' || $5::text || '%' OR 
       c.phone ILIKE '%' || $5::text || '%')
`

type CountCandidatesParams struct {
	JobID        pgtype.UUID `json:"job_id"`
	ReviewerID   pgtype.UUID `json:"reviewer_id"`
	ReviewStatus pgtype.Text `json:"review_status"`
	Status       pgtype.Text `json:"status"`
	Search       pgtype.Text `json:"search"`
}

func (q *Queries) CountCandidates(ctx context.Context, arg CountCandidatesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCandidates,
		arg.JobID,
		arg.ReviewerID,
		arg.ReviewStatus,
		arg.Status,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmployees = `-- name: CountEmployees :one
SELECT COUNT(*) FROM employees e
JOIN users u ON e.user_id = u.id
WHERE ($1::varchar IS NULL OR e.status = $1)
  AND ($2::varchar IS NULL OR e.department = $2)
  AND ($3::varchar IS NULL OR e.first_name ILIKE '%' || $3 || '%' OR e.last_name ILIKE '%' || $3 || '%' OR e.email ILIKE '%' || $3 || '%')
  AND u.is_admin = false
`

type CountEmployeesParams struct {
	Status     pgtype.Text `json:"status"`
	Department pgtype.Text `json:"department"`
	Search     pgtype.Text `json:"search"`
}

func (q *Queries) CountEmployees(ctx context.Context, arg CountEmployeesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployees, arg.Status, arg.Department, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInterviews = `-- name: CountInterviews :one
SELECT COUNT(*)
FROM interviews i
WHERE 
    ($1::timestamptz IS NULL OR i.scheduled_time >= $1)
    AND ($2::timestamptz IS NULL OR i.scheduled_time <= $2)
    AND ($3::text[] IS NULL OR i.status = ANY($3::text[]))
`

type CountInterviewsParams struct {
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
	Statuses  []string           `json:"statuses"`
}

func (q *Queries) CountInterviews(ctx context.Context, arg CountInterviewsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInterviews, arg.StartTime, arg.EndTime, arg.Statuses)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCandidate = `-- name: CreateCandidate :one
INSERT INTO candidates (
  name, avatar, email, phone, experience_years, education, applied_job_id, channel, resume_url, status, applied_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, name, avatar, email, phone, experience_years, education, applied_job_id, channel, resume_url, status, applied_at, created_at, updated_at, reviewer_id, review_status
`

type CreateCandidateParams struct {
	Name            string             `json:"name"`
	Avatar          pgtype.Text        `json:"avatar"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	ExperienceYears int32              `json:"experience_years"`
	Education       string             `json:"education"`
	AppliedJobID    pgtype.UUID        `json:"applied_job_id"`
	Channel         string             `json:"channel"`
	ResumeUrl       string             `json:"resume_url"`
	Status          string             `json:"status"`
	AppliedAt       pgtype.Timestamptz `json:"applied_at"`
}

func (q *Queries) CreateCandidate(ctx context.Context, arg CreateCandidateParams) (Candidate, error) {
	row := q.db.QueryRow(ctx, createCandidate,
		arg.Name,
		arg.Avatar,
		arg.Email,
		arg.Phone,
		arg.ExperienceYears,
		arg.Education,
		arg.AppliedJobID,
		arg.Channel,
		arg.ResumeUrl,
		arg.Status,
		arg.AppliedAt,
	)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.ExperienceYears,
		&i.Education,
		&i.AppliedJobID,
		&i.Channel,
		&i.ResumeUrl,
		&i.Status,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewerID,
		&i.ReviewStatus,
	)
	return i, err
}

const createCandidateComment = `-- name: CreateCandidateComment :one

INSERT INTO candidate_comments (
    candidate_id, author_id, content, comment_type
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, candidate_id, author_id, content, created_at, comment_type
`

type CreateCandidateCommentParams struct {
	CandidateID pgtype.UUID `json:"candidate_id"`
	AuthorID    pgtype.UUID `json:"author_id"`
	Content     string      `json:"content"`
	CommentType string      `json:"comment_type"`
}

// Candidate Comment queries
func (q *Queries) CreateCandidateComment(ctx context.Context, arg CreateCandidateCommentParams) (CandidateComment, error) {
	row := q.db.QueryRow(ctx, createCandidateComment,
		arg.CandidateID,
		arg.AuthorID,
		arg.Content,
		arg.CommentType,
	)
	var i CandidateComment
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.CommentType,
	)
	return i, err
}

const createCandidateStatus = `-- name: CreateCandidateStatus :one
INSERT INTO candidate_statuses (
    name, slug, type, sort_order, color
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, name, slug, type, sort_order, color, created_at, updated_at, is_deleted
`

type CreateCandidateStatusParams struct {
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	Type      string `json:"type"`
	SortOrder int32  `json:"sort_order"`
	Color     string `json:"color"`
}

func (q *Queries) CreateCandidateStatus(ctx context.Context, arg CreateCandidateStatusParams) (CandidateStatus, error) {
	row := q.db.QueryRow(ctx, createCandidateStatus,
		arg.Name,
		arg.Slug,
		arg.Type,
		arg.SortOrder,
		arg.Color,
	)
	var i CandidateStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.SortOrder,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const createEmployee = `-- name: CreateEmployee :one

INSERT INTO employees (
  first_name, last_name, email, phone, department, position, status, employment_type, join_date, manager_id, user_id, employee_type
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, first_name, last_name, email, phone, department, position, status, employment_type, join_date, manager_id, user_id, created_at, updated_at, employee_type
`

type CreateEmployeeParams struct {
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	Email          string             `json:"email"`
	Phone          string             `json:"phone"`
	Department     string             `json:"department"`
	Position       string             `json:"position"`
	Status         string             `json:"status"`
	EmploymentType string             `json:"employment_type"`
	JoinDate       pgtype.Timestamptz `json:"join_date"`
	ManagerID      pgtype.UUID        `json:"manager_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	EmployeeType   string             `json:"employee_type"`
}

// Employee queries
func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Department,
		arg.Position,
		arg.Status,
		arg.EmploymentType,
		arg.JoinDate,
		arg.ManagerID,
		arg.UserID,
		arg.EmployeeType,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Department,
		&i.Position,
		&i.Status,
		&i.EmploymentType,
		&i.JoinDate,
		&i.ManagerID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmployeeType,
	)
	return i, err
}

const createInterview = `-- name: CreateInterview :one

WITH current_candidate_status AS (
    SELECT s.id, s.slug, s.name
    FROM candidate_statuses s
    JOIN candidates c ON c.status = s.slug
    WHERE c.id = $1
),
inserted_interview AS (
    INSERT INTO interviews (
      candidate_id, interviewer_id, job_id, scheduled_time, scheduled_end_time, status, candidate_status_id, snapshot_status_key, snapshot_status_label
    ) VALUES (
      $1, $2, $3, $4, $5, $6, 
      (SELECT id FROM current_candidate_status),
      (SELECT slug FROM current_candidate_status),
      (SELECT name FROM current_candidate_status)
    )
    ON CONFLICT (candidate_id, job_id) WHERE status = 'PENDING'
    DO UPDATE SET
      interviewer_id = EXCLUDED.interviewer_id,
      job_id = EXCLUDED.job_id,
      scheduled_time = EXCLUDED.scheduled_time,
      scheduled_end_time = EXCLUDED.scheduled_end_time,
      candidate_status_id = EXCLUDED.candidate_status_id,
      snapshot_status_key = EXCLUDED.snapshot_status_key,
      snapshot_status_label = EXCLUDED.snapshot_status_label,
      updated_at = CURRENT_TIMESTAMP
    RETURNING id, candidate_id, interviewer_id, job_id, scheduled_time, status, created_at, updated_at, scheduled_end_time, candidate_status_id, snapshot_status_key, snapshot_status_label
)
SELECT id, candidate_id, interviewer_id, job_id, scheduled_time, status, created_at, updated_at, scheduled_end_time, candidate_status_id, snapshot_status_key, snapshot_status_label FROM inserted_interview
`

type CreateInterviewParams struct {
	ID               pgtype.UUID        `json:"id"`
	InterviewerID    pgtype.UUID        `json:"interviewer_id"`
	JobID            pgtype.UUID        `json:"job_id"`
	ScheduledTime    pgtype.Timestamptz `json:"scheduled_time"`
	ScheduledEndTime pgtype.Timestamptz `json:"scheduled_end_time"`
	Status           string             `json:"status"`
}

type CreateInterviewRow struct {
	ID                  pgtype.UUID        `json:"id"`
	CandidateID         pgtype.UUID        `json:"candidate_id"`
	InterviewerID       pgtype.UUID        `json:"interviewer_id"`
	JobID               pgtype.UUID        `json:"job_id"`
	ScheduledTime       pgtype.Timestamptz `json:"scheduled_time"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ScheduledEndTime    pgtype.Timestamptz `json:"scheduled_end_time"`
	CandidateStatusID   pgtype.UUID        `json:"candidate_status_id"`
	SnapshotStatusKey   string             `json:"snapshot_status_key"`
	SnapshotStatusLabel string             `json:"snapshot_status_label"`
}

// Interview queries
func (q *Queries) CreateInterview(ctx context.Context, arg CreateInterviewParams) (CreateInterviewRow, error) {
	row := q.db.QueryRow(ctx, createInterview,
		arg.ID,
		arg.InterviewerID,
		arg.JobID,
		arg.ScheduledTime,
		arg.ScheduledEndTime,
		arg.Status,
	)
	var i CreateInterviewRow
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.InterviewerID,
		&i.JobID,
		&i.ScheduledTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScheduledEndTime,
		&i.CandidateStatusID,
		&i.SnapshotStatusKey,
		&i.SnapshotStatusLabel,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
  title, department, head_count, open_date, job_description, note, status
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, title, department, head_count, open_date, job_description, note, status, created_at, updated_at
`

type CreateJobParams struct {
	Title          string             `json:"title"`
	Department     string             `json:"department"`
	HeadCount      int32              `json:"head_count"`
	OpenDate       pgtype.Timestamptz `json:"open_date"`
	JobDescription string             `json:"job_description"`
	Note           pgtype.Text        `json:"note"`
	Status         string             `json:"status"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Title,
		arg.Department,
		arg.HeadCount,
		arg.OpenDate,
		arg.JobDescription,
		arg.Note,
		arg.Status,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Department,
		&i.HeadCount,
		&i.OpenDate,
		&i.JobDescription,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (
  user_id, device_info, ip_address, user_agent, expires_at
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, user_id, device_info, ip_address, user_agent, created_at, expires_at, is_active, last_active_at
`

type CreateSessionParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	DeviceInfo []byte             `json:"device_info"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

// Session queries
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.DeviceInfo,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsActive,
		&i.LastActiveAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, avatar)
VALUES ($1, $2, $3, $4)
RETURNING id, username, email, password_hash, avatar, created_at, updated_at, is_admin
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Avatar       pgtype.Text `json:"avatar"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Avatar,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const deactivateSession = `-- name: DeactivateSession :exec
UPDATE sessions
SET is_active = false
WHERE id = $1
`

func (q *Queries) DeactivateSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateSession, id)
	return err
}

const deactivateUserSessions = `-- name: DeactivateUserSessions :exec
UPDATE sessions
SET is_active = false
WHERE user_id = $1
`

func (q *Queries) DeactivateUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUserSessions, userID)
	return err
}

const deleteCandidate = `-- name: DeleteCandidate :exec
DELETE FROM candidates
WHERE id = $1
`

func (q *Queries) DeleteCandidate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCandidate, id)
	return err
}

const deleteCandidateComment = `-- name: DeleteCandidateComment :exec
DELETE FROM candidate_comments WHERE id = $1
`

func (q *Queries) DeleteCandidateComment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCandidateComment, id)
	return err
}

const deleteCandidateStatus = `-- name: DeleteCandidateStatus :exec
UPDATE candidate_statuses
SET is_deleted = true,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeleteCandidateStatus(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCandidateStatus, id)
	return err
}

const deleteEmployee = `-- name: DeleteEmployee :exec
DELETE FROM employees
WHERE id = $1
`

func (q *Queries) DeleteEmployee(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmployee, id)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions 
WHERE expires_at IS NOT NULL AND expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteInactiveSessions = `-- name: DeleteInactiveSessions :exec
DELETE FROM sessions 
WHERE last_active_at < $1
`

func (q *Queries) DeleteInactiveSessions(ctx context.Context, lastActiveAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteInactiveSessions, lastActiveAt)
	return err
}

const deleteInterview = `-- name: DeleteInterview :execrows
DELETE FROM interviews
WHERE id = $1
  AND status = 'PENDING'
`

func (q *Queries) DeleteInterview(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInterview, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getActiveInterviewCount = `-- name: GetActiveInterviewCount :one
SELECT COUNT(*) FROM interviews 
WHERE interviewer_id = $1 AND status = 'PENDING'
`

func (q *Queries) GetActiveInterviewCount(ctx context.Context, interviewerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getActiveInterviewCount, interviewerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveSessionByID = `-- name: GetActiveSessionByID :one
SELECT id, user_id, device_info, ip_address, user_agent, created_at, expires_at, is_active, last_active_at FROM sessions WHERE id = $1 AND is_active = true AND (expires_at IS NULL OR expires_at > CURRENT_TIMESTAMP) LIMIT 1
`

func (q *Queries) GetActiveSessionByID(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsActive,
		&i.LastActiveAt,
	)
	return i, err
}

const getCandidate = `-- name: GetCandidate :one
SELECT 
    c.id, c.name, c.avatar, c.email, c.phone, c.experience_years, c.education, c.applied_job_id, c.channel, c.resume_url, c.status, c.applied_at, c.created_at, c.updated_at, c.reviewer_id, c.review_status, 
    j.title as applied_job_title,
    e.first_name as reviewer_first_name,
    e.last_name as reviewer_last_name
FROM candidates c
JOIN jobs j ON c.applied_job_id = j.id
LEFT JOIN employees e ON c.reviewer_id = e.id
WHERE c.id = $1 LIMIT 1
`

type GetCandidateRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Avatar            pgtype.Text        `json:"avatar"`
	Email             string             `json:"email"`
	Phone             string             `json:"phone"`
	ExperienceYears   int32              `json:"experience_years"`
	Education         string             `json:"education"`
	AppliedJobID      pgtype.UUID        `json:"applied_job_id"`
	Channel           string             `json:"channel"`
	ResumeUrl         string             `json:"resume_url"`
	Status            string             `json:"status"`
	AppliedAt         pgtype.Timestamptz `json:"applied_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ReviewerID        pgtype.UUID        `json:"reviewer_id"`
	ReviewStatus      pgtype.Text        `json:"review_status"`
	AppliedJobTitle   string             `json:"applied_job_title"`
	ReviewerFirstName pgtype.Text        `json:"reviewer_first_name"`
	ReviewerLastName  pgtype.Text        `json:"reviewer_last_name"`
}

func (q *Queries) GetCandidate(ctx context.Context, id pgtype.UUID) (GetCandidateRow, error) {
	row := q.db.QueryRow(ctx, getCandidate, id)
	var i GetCandidateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.ExperienceYears,
		&i.Education,
		&i.AppliedJobID,
		&i.Channel,
		&i.ResumeUrl,
		&i.Status,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewerID,
		&i.ReviewStatus,
		&i.AppliedJobTitle,
		&i.ReviewerFirstName,
		&i.ReviewerLastName,
	)
	return i, err
}

const getCandidateComment = `-- name: GetCandidateComment :one
SELECT id, candidate_id, author_id, content, created_at, comment_type FROM candidate_comments WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCandidateComment(ctx context.Context, id pgtype.UUID) (CandidateComment, error) {
	row := q.db.QueryRow(ctx, getCandidateComment, id)
	var i CandidateComment
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.CommentType,
	)
	return i, err
}

const getCandidateCountsByJob = `-- name: GetCandidateCountsByJob :many
SELECT applied_job_id, COUNT(*) as count
FROM candidates
GROUP BY applied_job_id
`

type GetCandidateCountsByJobRow struct {
	AppliedJobID pgtype.UUID `json:"applied_job_id"`
	Count        int64       `json:"count"`
}

func (q *Queries) GetCandidateCountsByJob(ctx context.Context) ([]GetCandidateCountsByJobRow, error) {
	rows, err := q.db.Query(ctx, getCandidateCountsByJob)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCandidateCountsByJobRow
	for rows.Next() {
		var i GetCandidateCountsByJobRow
		if err := rows.Scan(&i.AppliedJobID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCandidateHistory = `-- name: GetCandidateHistory :many
SELECT 
    c.id as candidate_id,
    c.name as candidate_name,
    c.status as status,
    COALESCE(cr.review_status, 'pending') as review_status,
    c.applied_at as applied_at,
    j.title as job_title
FROM candidates c
JOIN jobs j ON c.applied_job_id = j.id
LEFT JOIN candidate_reviewers cr ON cr.candidate_id = c.id AND cr.removed_at IS NULL
WHERE (c.email = (SELECT email FROM candidates WHERE id = $1::uuid)
   OR c.phone = (SELECT phone FROM candidates WHERE id = $1::uuid))
ORDER BY c.applied_at DESC
`

type GetCandidateHistoryRow struct {
	CandidateID   pgtype.UUID        `json:"candidate_id"`
	CandidateName string             `json:"candidate_name"`
	Status        string             `json:"status"`
	ReviewStatus  string             `json:"review_status"`
	AppliedAt     pgtype.Timestamptz `json:"applied_at"`
	JobTitle      string             `json:"job_title"`
}

func (q *Queries) GetCandidateHistory(ctx context.Context, dollar_1 pgtype.UUID) ([]GetCandidateHistoryRow, error) {
	rows, err := q.db.Query(ctx, getCandidateHistory, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCandidateHistoryRow
	for rows.Next() {
		var i GetCandidateHistoryRow
		if err := rows.Scan(
			&i.CandidateID,
			&i.CandidateName,
			&i.Status,
			&i.ReviewStatus,
			&i.AppliedAt,
			&i.JobTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCandidateHistoryForReviewer = `-- name: GetCandidateHistoryForReviewer :many
SELECT 
    c.id as candidate_id,
    c.name as candidate_name,
    c.status as status,
    cr.review_status as review_status,
    c.applied_at as applied_at,
    j.title as job_title
FROM candidates c
JOIN jobs j ON c.applied_job_id = j.id
JOIN candidate_reviewers cr ON cr.candidate_id = c.id
WHERE (c.email = (SELECT email FROM candidates WHERE id = $1::uuid)
   OR c.phone = (SELECT phone FROM candidates WHERE id = $1::uuid))
  AND cr.reviewer_id = $2::uuid
  AND cr.review_status != 'pending'
ORDER BY c.applied_at DESC
`

type GetCandidateHistoryForReviewerParams struct {
	CandidateID pgtype.UUID `json:"candidate_id"`
	ReviewerID  pgtype.UUID `json:"reviewer_id"`
}

type GetCandidateHistoryForReviewerRow struct {
	CandidateID   pgtype.UUID        `json:"candidate_id"`
	CandidateName string             `json:"candidate_name"`
	Status        string             `json:"status"`
	ReviewStatus  string             `json:"review_status"`
	AppliedAt     pgtype.Timestamptz `json:"applied_at"`
	JobTitle      string             `json:"job_title"`
}

func (q *Queries) GetCandidateHistoryForReviewer(ctx context.Context, arg GetCandidateHistoryForReviewerParams) ([]GetCandidateHistoryForReviewerRow, error) {
	rows, err := q.db.Query(ctx, getCandidateHistoryForReviewer, arg.CandidateID, arg.ReviewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCandidateHistoryForReviewerRow
	for rows.Next() {
		var i GetCandidateHistoryForReviewerRow
		if err := rows.Scan(
			&i.CandidateID,
			&i.CandidateName,
			&i.Status,
			&i.ReviewStatus,
			&i.AppliedAt,
			&i.JobTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCandidateReviewerForRevert = `-- name: GetCandidateReviewerForRevert :one
SELECT id, candidate_id, reviewer_id, assigned_at, removed_at, created_at, review_status, reviewed_at, assigned_by_user_id
FROM candidate_reviewers
WHERE candidate_id = $1
ORDER BY assigned_at DESC
LIMIT 1
`

func (q *Queries) GetCandidateReviewerForRevert(ctx context.Context, candidateID pgtype.UUID) (CandidateReviewer, error) {
	row := q.db.QueryRow(ctx, getCandidateReviewerForRevert, candidateID)
	var i CandidateReviewer
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.ReviewerID,
		&i.AssignedAt,
		&i.RemovedAt,
		&i.CreatedAt,
		&i.ReviewStatus,
		&i.ReviewedAt,
		&i.AssignedByUserID,
	)
	return i, err
}

const getCandidateStatus = `-- name: GetCandidateStatus :one
SELECT id, name, slug, type, sort_order, color, created_at, updated_at, is_deleted FROM candidate_statuses
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCandidateStatus(ctx context.Context, id pgtype.UUID) (CandidateStatus, error) {
	row := q.db.QueryRow(ctx, getCandidateStatus, id)
	var i CandidateStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.SortOrder,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getCandidateStatusBySlug = `-- name: GetCandidateStatusBySlug :one
SELECT id, name, slug, type, sort_order, color, created_at, updated_at, is_deleted FROM candidate_statuses
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetCandidateStatusBySlug(ctx context.Context, slug string) (CandidateStatus, error) {
	row := q.db.QueryRow(ctx, getCandidateStatusBySlug, slug)
	var i CandidateStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.SortOrder,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getCurrentCandidateReviewer = `-- name: GetCurrentCandidateReviewer :one
SELECT id, candidate_id, reviewer_id, assigned_at, removed_at, created_at, review_status, reviewed_at, assigned_by_user_id
FROM candidate_reviewers
WHERE candidate_id = $1 AND removed_at IS NULL
ORDER BY assigned_at DESC
FOR UPDATE
LIMIT 1
`

func (q *Queries) GetCurrentCandidateReviewer(ctx context.Context, candidateID pgtype.UUID) (CandidateReviewer, error) {
	row := q.db.QueryRow(ctx, getCurrentCandidateReviewer, candidateID)
	var i CandidateReviewer
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.ReviewerID,
		&i.AssignedAt,
		&i.RemovedAt,
		&i.CreatedAt,
		&i.ReviewStatus,
		&i.ReviewedAt,
		&i.AssignedByUserID,
	)
	return i, err
}

const getEmployee = `-- name: GetEmployee :one
SELECT id, first_name, last_name, email, phone, department, position, status, employment_type, join_date, manager_id, user_id, created_at, updated_at, employee_type FROM employees
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEmployee(ctx context.Context, id pgtype.UUID) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployee, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Department,
		&i.Position,
		&i.Status,
		&i.EmploymentType,
		&i.JoinDate,
		&i.ManagerID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmployeeType,
	)
	return i, err
}

const getEmployeeByUserID = `-- name: GetEmployeeByUserID :one
SELECT id, first_name, last_name, email, phone, department, position, status, employment_type, join_date, manager_id, user_id, created_at, updated_at, employee_type FROM employees WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetEmployeeByUserID(ctx context.Context, userID pgtype.UUID) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByUserID, userID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Department,
		&i.Position,
		&i.Status,
		&i.EmploymentType,
		&i.JoinDate,
		&i.ManagerID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmployeeType,
	)
	return i, err
}

const getInterview = `-- name: GetInterview :one
SELECT i.id, i.candidate_id, i.interviewer_id, i.job_id, i.scheduled_time, i.status, i.created_at, i.updated_at, i.scheduled_end_time, i.candidate_status_id, i.snapshot_status_key, i.snapshot_status_label
FROM interviews i
WHERE i.id = $1 LIMIT 1
`

func (q *Queries) GetInterview(ctx context.Context, id pgtype.UUID) (Interview, error) {
	row := q.db.QueryRow(ctx, getInterview, id)
	var i Interview
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.InterviewerID,
		&i.JobID,
		&i.ScheduledTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScheduledEndTime,
		&i.CandidateStatusID,
		&i.SnapshotStatusKey,
		&i.SnapshotStatusLabel,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, title, department, head_count, open_date, job_description, note, status, created_at, updated_at FROM jobs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetJob(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Department,
		&i.HeadCount,
		&i.OpenDate,
		&i.JobDescription,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPastReviewedCandidates = `-- name: GetPastReviewedCandidates :many
SELECT
  c.id,
  c.name,
  c.avatar,
  c.email,
  c.phone,
  c.experience_years,
  c.education,
  c.applied_job_id,
  c.channel,
  c.resume_url,
  c.status,
  c.applied_at,
  c.created_at,
  c.updated_at,
  cr.reviewer_id,
  cr.review_status,
  j.title as applied_job_title,
  cr.assigned_at,
  cr.removed_at,
  cr.reviewed_at
FROM candidate_reviewers cr
JOIN candidates c ON cr.candidate_id = c.id
JOIN jobs j ON c.applied_job_id = j.id
WHERE cr.reviewer_id = $1
  AND cr.review_status != 'pending'
ORDER BY cr.reviewed_at DESC NULLS LAST, cr.assigned_at DESC, c.id DESC
`

type GetPastReviewedCandidatesRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Avatar          pgtype.Text        `json:"avatar"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	ExperienceYears int32              `json:"experience_years"`
	Education       string             `json:"education"`
	AppliedJobID    pgtype.UUID        `json:"applied_job_id"`
	Channel         string             `json:"channel"`
	ResumeUrl       string             `json:"resume_url"`
	Status          string             `json:"status"`
	AppliedAt       pgtype.Timestamptz `json:"applied_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ReviewerID      pgtype.UUID        `json:"reviewer_id"`
	ReviewStatus    string             `json:"review_status"`
	AppliedJobTitle string             `json:"applied_job_title"`
	AssignedAt      pgtype.Timestamp   `json:"assigned_at"`
	RemovedAt       pgtype.Timestamp   `json:"removed_at"`
	ReviewedAt      pgtype.Timestamptz `json:"reviewed_at"`
}

func (q *Queries) GetPastReviewedCandidates(ctx context.Context, reviewerID pgtype.UUID) ([]GetPastReviewedCandidatesRow, error) {
	rows, err := q.db.Query(ctx, getPastReviewedCandidates, reviewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPastReviewedCandidatesRow
	for rows.Next() {
		var i GetPastReviewedCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Avatar,
			&i.Email,
			&i.Phone,
			&i.ExperienceYears,
			&i.Education,
			&i.AppliedJobID,
			&i.Channel,
			&i.ResumeUrl,
			&i.Status,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReviewerID,
			&i.ReviewStatus,
			&i.AppliedJobTitle,
			&i.AssignedAt,
			&i.RemovedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewerAssignment = `-- name: GetReviewerAssignment :one
SELECT id, candidate_id, reviewer_id, assigned_at, removed_at, created_at, review_status, reviewed_at, assigned_by_user_id
FROM candidate_reviewers
WHERE candidate_id = $1
  AND reviewer_id = $2
  AND removed_at IS NULL
ORDER BY assigned_at DESC
FOR UPDATE
LIMIT 1
`

type GetReviewerAssignmentParams struct {
	CandidateID pgtype.UUID `json:"candidate_id"`
	ReviewerID  pgtype.UUID `json:"reviewer_id"`
}

func (q *Queries) GetReviewerAssignment(ctx context.Context, arg GetReviewerAssignmentParams) (CandidateReviewer, error) {
	row := q.db.QueryRow(ctx, getReviewerAssignment, arg.CandidateID, arg.ReviewerID)
	var i CandidateReviewer
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.ReviewerID,
		&i.AssignedAt,
		&i.RemovedAt,
		&i.CreatedAt,
		&i.ReviewStatus,
		&i.ReviewedAt,
		&i.AssignedByUserID,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, device_info, ip_address, user_agent, created_at, expires_at, is_active, last_active_at FROM sessions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsActive,
		&i.LastActiveAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, avatar, created_at, updated_at, is_admin FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, avatar, created_at, updated_at, is_admin FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const getUserSessions = `-- name: GetUserSessions :many
SELECT id, user_id, device_info, ip_address, user_agent, created_at, expires_at, is_active, last_active_at FROM sessions 
WHERE user_id = $1 AND is_active = true AND (expires_at IS NULL OR expires_at > CURRENT_TIMESTAMP)
ORDER BY created_at DESC
`

func (q *Queries) GetUserSessions(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, getUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceInfo,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.IsActive,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasInterviewAssignments = `-- name: HasInterviewAssignments :one
SELECT EXISTS(SELECT 1 FROM interviews WHERE interviewer_id = $1)
`

func (q *Queries) HasInterviewAssignments(ctx context.Context, interviewerID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasInterviewAssignments, interviewerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertCandidateReviewer = `-- name: InsertCandidateReviewer :one
INSERT INTO candidate_reviewers (candidate_id, reviewer_id, assigned_by_user_id)
VALUES ($1, $2, $3)
RETURNING id, candidate_id, reviewer_id, assigned_at, removed_at, created_at, review_status, reviewed_at, assigned_by_user_id
`

type InsertCandidateReviewerParams struct {
	CandidateID      pgtype.UUID `json:"candidate_id"`
	ReviewerID       pgtype.UUID `json:"reviewer_id"`
	AssignedByUserID pgtype.UUID `json:"assigned_by_user_id"`
}

func (q *Queries) InsertCandidateReviewer(ctx context.Context, arg InsertCandidateReviewerParams) (CandidateReviewer, error) {
	row := q.db.QueryRow(ctx, insertCandidateReviewer, arg.CandidateID, arg.ReviewerID, arg.AssignedByUserID)
	var i CandidateReviewer
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.ReviewerID,
		&i.AssignedAt,
		&i.RemovedAt,
		&i.CreatedAt,
		&i.ReviewStatus,
		&i.ReviewedAt,
		&i.AssignedByUserID,
	)
	return i, err
}

const isCandidateReviewer = `-- name: IsCandidateReviewer :one
SELECT id
FROM candidate_reviewers
WHERE candidate_id = $1
  AND reviewer_id = $2
  AND removed_at IS NULL
LIMIT 1
`

type IsCandidateReviewerParams struct {
	CandidateID pgtype.UUID `json:"candidate_id"`
	ReviewerID  pgtype.UUID `json:"reviewer_id"`
}

func (q *Queries) IsCandidateReviewer(ctx context.Context, arg IsCandidateReviewerParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, isCandidateReviewer, arg.CandidateID, arg.ReviewerID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listCandidateComments = `-- name: ListCandidateComments :many
SELECT 
    cc.id, cc.candidate_id, cc.author_id, cc.content, cc.created_at, cc.comment_type,
    e.first_name || ' ' || e.last_name as author_name,
    u.avatar as author_avatar,
    CASE 
        WHEN e.employee_type = 'HR' OR rr.employee_id IS NOT NULL THEN 'HR'
        ELSE 'INTERVIEWER'
    END as author_role
FROM candidate_comments cc
JOIN employees e ON cc.author_id = e.id
JOIN users u ON e.user_id = u.id
LEFT JOIN recruitment_roles rr ON e.id = rr.employee_id AND rr.role_type = 'RECRUITER'
WHERE cc.candidate_id = $1
ORDER BY cc.created_at DESC
`

type ListCandidateCommentsRow struct {
	ID           pgtype.UUID        `json:"id"`
	CandidateID  pgtype.UUID        `json:"candidate_id"`
	AuthorID     pgtype.UUID        `json:"author_id"`
	Content      string             `json:"content"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CommentType  string             `json:"comment_type"`
	AuthorName   interface{}        `json:"author_name"`
	AuthorAvatar pgtype.Text        `json:"author_avatar"`
	AuthorRole   string             `json:"author_role"`
}

func (q *Queries) ListCandidateComments(ctx context.Context, candidateID pgtype.UUID) ([]ListCandidateCommentsRow, error) {
	rows, err := q.db.Query(ctx, listCandidateComments, candidateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCandidateCommentsRow
	for rows.Next() {
		var i ListCandidateCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CandidateID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.CommentType,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCandidateStatuses = `-- name: ListCandidateStatuses :many

SELECT id, name, slug, type, sort_order, color, created_at, updated_at, is_deleted FROM candidate_statuses
WHERE is_deleted = false
ORDER BY sort_order ASC
`

// Candidate Status queries
func (q *Queries) ListCandidateStatuses(ctx context.Context) ([]CandidateStatus, error) {
	rows, err := q.db.Query(ctx, listCandidateStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CandidateStatus
	for rows.Next() {
		var i CandidateStatus
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.SortOrder,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCandidates = `-- name: ListCandidates :many
SELECT 
    c.id, c.name, c.avatar, c.email, c.phone, c.experience_years, c.education, c.applied_job_id, c.channel, c.resume_url, c.status, c.applied_at, c.created_at, c.updated_at, c.reviewer_id, c.review_status, 
    j.title as applied_job_title,
    e.first_name as reviewer_first_name,
    e.last_name as reviewer_last_name
FROM candidates c
JOIN jobs j ON c.applied_job_id = j.id
LEFT JOIN employees e ON c.reviewer_id = e.id
WHERE ($3::uuid IS NULL OR c.applied_job_id = $3)
  AND ($4::uuid IS NULL OR c.reviewer_id = $4)
  AND ($5::text IS NULL OR c.review_status = $5)
  AND ($6::text IS NULL OR c.status = $6)
  AND ($7::text IS NULL OR 
    c.name ILIKE '%' || $7::text || '%' OR 
    c.email ILIKE '%' || $7::text || '%' OR 
    c.phone ILIKE '%' || $7::text || '%')
ORDER BY c.applied_at DESC
LIMIT $1 OFFSET $2
`

type ListCandidatesParams struct {
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
	JobID        pgtype.UUID `json:"job_id"`
	ReviewerID   pgtype.UUID `json:"reviewer_id"`
	ReviewStatus pgtype.Text `json:"review_status"`
	Status       pgtype.Text `json:"status"`
	Search       pgtype.Text `json:"search"`
}

type ListCandidatesRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Avatar            pgtype.Text        `json:"avatar"`
	Email             string             `json:"email"`
	Phone             string             `json:"phone"`
	ExperienceYears   int32              `json:"experience_years"`
	Education         string             `json:"education"`
	AppliedJobID      pgtype.UUID        `json:"applied_job_id"`
	Channel           string             `json:"channel"`
	ResumeUrl         string             `json:"resume_url"`
	Status            string             `json:"status"`
	AppliedAt         pgtype.Timestamptz `json:"applied_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ReviewerID        pgtype.UUID        `json:"reviewer_id"`
	ReviewStatus      pgtype.Text        `json:"review_status"`
	AppliedJobTitle   string             `json:"applied_job_title"`
	ReviewerFirstName pgtype.Text        `json:"reviewer_first_name"`
	ReviewerLastName  pgtype.Text        `json:"reviewer_last_name"`
}

func (q *Queries) ListCandidates(ctx context.Context, arg ListCandidatesParams) ([]ListCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listCandidates,
		arg.Limit,
		arg.Offset,
		arg.JobID,
		arg.ReviewerID,
		arg.ReviewStatus,
		arg.Status,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCandidatesRow
	for rows.Next() {
		var i ListCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Avatar,
			&i.Email,
			&i.Phone,
			&i.ExperienceYears,
			&i.Education,
			&i.AppliedJobID,
			&i.Channel,
			&i.ResumeUrl,
			&i.Status,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReviewerID,
			&i.ReviewStatus,
			&i.AppliedJobTitle,
			&i.ReviewerFirstName,
			&i.ReviewerLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployees = `-- name: ListEmployees :many
SELECT e.id, e.first_name, e.last_name, e.email, e.phone, e.department, e.position, e.status, e.employment_type, e.join_date, e.manager_id, e.user_id, e.created_at, e.updated_at, e.employee_type FROM employees e
JOIN users u ON e.user_id = u.id
WHERE ($1::varchar IS NULL OR e.status = $1)
  AND ($2::varchar IS NULL OR e.department = $2)
  AND ($3::varchar IS NULL OR e.first_name ILIKE '%' || $3 || '%' OR e.last_name ILIKE '%' || $3 || '%' OR e.email ILIKE '%' || $3 || '%')
  AND u.is_admin = false
ORDER BY e.created_at DESC
LIMIT $5 OFFSET $4
`

type ListEmployeesParams struct {
	Status     pgtype.Text `json:"status"`
	Department pgtype.Text `json:"department"`
	Search     pgtype.Text `json:"search"`
	OffsetVal  int32       `json:"offset_val"`
	LimitVal   int32       `json:"limit_val"`
}

func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployees,
		arg.Status,
		arg.Department,
		arg.Search,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Department,
			&i.Position,
			&i.Status,
			&i.EmploymentType,
			&i.JoinDate,
			&i.ManagerID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHRs = `-- name: ListHRs :many
SELECT e.id, e.first_name, e.last_name, e.department, e.phone
FROM employees e
JOIN users u ON e.user_id = u.id
WHERE e.employee_type = 'HR' AND u.is_admin = false
ORDER BY e.first_name
`

type ListHRsRow struct {
	ID         pgtype.UUID `json:"id"`
	FirstName  string      `json:"first_name"`
	LastName   string      `json:"last_name"`
	Department string      `json:"department"`
	Phone      string      `json:"phone"`
}

func (q *Queries) ListHRs(ctx context.Context) ([]ListHRsRow, error) {
	rows, err := q.db.Query(ctx, listHRs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHRsRow
	for rows.Next() {
		var i ListHRsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Department,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInterviewers = `-- name: ListInterviewers :many
SELECT e.id, e.first_name, e.last_name, e.department, e.phone
FROM recruitment_roles rr
JOIN employees e ON rr.employee_id = e.id
JOIN users u ON e.user_id = u.id
WHERE u.is_admin = false
  AND rr.role_type = 'INTERVIEWER'
ORDER BY e.first_name
`

type ListInterviewersRow struct {
	ID         pgtype.UUID `json:"id"`
	FirstName  string      `json:"first_name"`
	LastName   string      `json:"last_name"`
	Department string      `json:"department"`
	Phone      string      `json:"phone"`
}

func (q *Queries) ListInterviewers(ctx context.Context) ([]ListInterviewersRow, error) {
	rows, err := q.db.Query(ctx, listInterviewers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInterviewersRow
	for rows.Next() {
		var i ListInterviewersRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Department,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInterviews = `-- name: ListInterviews :many
SELECT 
    i.id, i.candidate_id, i.interviewer_id, i.job_id, i.scheduled_time, i.status, i.created_at, i.updated_at, i.scheduled_end_time, i.candidate_status_id, i.snapshot_status_key, i.snapshot_status_label, 
    c.name as candidate_name, 
    c.resume_url as candidate_resume_url,
    j.title as job_title,
    e.first_name as interviewer_first_name, 
    e.last_name as interviewer_last_name
FROM interviews i
JOIN candidates c ON i.candidate_id = c.id
JOIN jobs j ON i.job_id = j.id
JOIN employees e ON i.interviewer_id = e.id
WHERE 
    ($3::timestamptz IS NULL OR i.scheduled_time >= $3)
    AND ($4::timestamptz IS NULL OR i.scheduled_time <= $4)
    AND ($5::text[] IS NULL OR i.status = ANY($5::text[]))
ORDER BY i.scheduled_time DESC
LIMIT $1 OFFSET $2
`

type ListInterviewsParams struct {
	Limit     int32              `json:"limit"`
	Offset    int32              `json:"offset"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
	Statuses  []string           `json:"statuses"`
}

type ListInterviewsRow struct {
	ID                   pgtype.UUID        `json:"id"`
	CandidateID          pgtype.UUID        `json:"candidate_id"`
	InterviewerID        pgtype.UUID        `json:"interviewer_id"`
	JobID                pgtype.UUID        `json:"job_id"`
	ScheduledTime        pgtype.Timestamptz `json:"scheduled_time"`
	Status               string             `json:"status"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ScheduledEndTime     pgtype.Timestamptz `json:"scheduled_end_time"`
	CandidateStatusID    pgtype.UUID        `json:"candidate_status_id"`
	SnapshotStatusKey    string             `json:"snapshot_status_key"`
	SnapshotStatusLabel  string             `json:"snapshot_status_label"`
	CandidateName        string             `json:"candidate_name"`
	CandidateResumeUrl   string             `json:"candidate_resume_url"`
	JobTitle             string             `json:"job_title"`
	InterviewerFirstName string             `json:"interviewer_first_name"`
	InterviewerLastName  string             `json:"interviewer_last_name"`
}

func (q *Queries) ListInterviews(ctx context.Context, arg ListInterviewsParams) ([]ListInterviewsRow, error) {
	rows, err := q.db.Query(ctx, listInterviews,
		arg.Limit,
		arg.Offset,
		arg.StartTime,
		arg.EndTime,
		arg.Statuses,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInterviewsRow
	for rows.Next() {
		var i ListInterviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.CandidateID,
			&i.InterviewerID,
			&i.JobID,
			&i.ScheduledTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ScheduledEndTime,
			&i.CandidateStatusID,
			&i.SnapshotStatusKey,
			&i.SnapshotStatusLabel,
			&i.CandidateName,
			&i.CandidateResumeUrl,
			&i.JobTitle,
			&i.InterviewerFirstName,
			&i.InterviewerLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInterviewsByInterviewer = `-- name: ListInterviewsByInterviewer :many
SELECT i.id, i.candidate_id, i.interviewer_id, i.job_id, i.scheduled_time, i.status, i.created_at, i.updated_at, i.scheduled_end_time, i.candidate_status_id, i.snapshot_status_key, i.snapshot_status_label
FROM interviews i
WHERE i.interviewer_id = $1
ORDER BY i.scheduled_time DESC
`

func (q *Queries) ListInterviewsByInterviewer(ctx context.Context, interviewerID pgtype.UUID) ([]Interview, error) {
	rows, err := q.db.Query(ctx, listInterviewsByInterviewer, interviewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Interview
	for rows.Next() {
		var i Interview
		if err := rows.Scan(
			&i.ID,
			&i.CandidateID,
			&i.InterviewerID,
			&i.JobID,
			&i.ScheduledTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ScheduledEndTime,
			&i.CandidateStatusID,
			&i.SnapshotStatusKey,
			&i.SnapshotStatusLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, title, department, head_count, open_date, job_description, note, status, created_at, updated_at FROM jobs
ORDER BY created_at DESC
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Department,
			&i.HeadCount,
			&i.OpenDate,
			&i.JobDescription,
			&i.Note,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingReviewCandidates = `-- name: ListPendingReviewCandidates :many
SELECT
  c.id,
  c.name,
  c.avatar,
  c.email,
  c.phone,
  c.experience_years,
  c.education,
  c.applied_job_id,
  c.channel,
  c.resume_url,
  c.status,
  c.applied_at,
  c.created_at,
  c.updated_at,
  cr.reviewer_id,
  cr.review_status,
  j.title as applied_job_title
FROM candidate_reviewers cr
JOIN candidates c ON cr.candidate_id = c.id
JOIN jobs j ON c.applied_job_id = j.id
WHERE cr.reviewer_id = $1
  AND cr.removed_at IS NULL
  AND cr.review_status = 'pending'
ORDER BY cr.assigned_at DESC
`

type ListPendingReviewCandidatesRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Avatar          pgtype.Text        `json:"avatar"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	ExperienceYears int32              `json:"experience_years"`
	Education       string             `json:"education"`
	AppliedJobID    pgtype.UUID        `json:"applied_job_id"`
	Channel         string             `json:"channel"`
	ResumeUrl       string             `json:"resume_url"`
	Status          string             `json:"status"`
	AppliedAt       pgtype.Timestamptz `json:"applied_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ReviewerID      pgtype.UUID        `json:"reviewer_id"`
	ReviewStatus    string             `json:"review_status"`
	AppliedJobTitle string             `json:"applied_job_title"`
}

func (q *Queries) ListPendingReviewCandidates(ctx context.Context, reviewerID pgtype.UUID) ([]ListPendingReviewCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listPendingReviewCandidates, reviewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingReviewCandidatesRow
	for rows.Next() {
		var i ListPendingReviewCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Avatar,
			&i.Email,
			&i.Phone,
			&i.ExperienceYears,
			&i.Education,
			&i.AppliedJobID,
			&i.Channel,
			&i.ResumeUrl,
			&i.Status,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReviewerID,
			&i.ReviewStatus,
			&i.AppliedJobTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecruiters = `-- name: ListRecruiters :many
SELECT e.id, e.first_name, e.last_name, e.department, e.phone
FROM recruitment_roles rr
JOIN employees e ON rr.employee_id = e.id
JOIN users u ON e.user_id = u.id
WHERE u.is_admin = false
  AND rr.role_type = 'RECRUITER'
ORDER BY e.first_name
`

type ListRecruitersRow struct {
	ID         pgtype.UUID `json:"id"`
	FirstName  string      `json:"first_name"`
	LastName   string      `json:"last_name"`
	Department string      `json:"department"`
	Phone      string      `json:"phone"`
}

func (q *Queries) ListRecruiters(ctx context.Context) ([]ListRecruitersRow, error) {
	rows, err := q.db.Query(ctx, listRecruiters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecruitersRow
	for rows.Next() {
		var i ListRecruitersRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Department,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewedCandidates = `-- name: ListReviewedCandidates :many
SELECT
  c.id,
  c.name,
  c.avatar,
  c.email,
  c.phone,
  c.experience_years,
  c.education,
  c.applied_job_id,
  c.channel,
  c.resume_url,
  c.status,
  c.applied_at,
  c.created_at,
  c.updated_at,
  cr.reviewer_id,
  cr.review_status,
  j.title as applied_job_title,
  cr.assigned_at,
  cr.removed_at
FROM candidate_reviewers cr
JOIN candidates c ON cr.candidate_id = c.id
JOIN jobs j ON c.applied_job_id = j.id
WHERE cr.reviewer_id = $1
ORDER BY cr.assigned_at DESC
`

type ListReviewedCandidatesRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Avatar          pgtype.Text        `json:"avatar"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	ExperienceYears int32              `json:"experience_years"`
	Education       string             `json:"education"`
	AppliedJobID    pgtype.UUID        `json:"applied_job_id"`
	Channel         string             `json:"channel"`
	ResumeUrl       string             `json:"resume_url"`
	Status          string             `json:"status"`
	AppliedAt       pgtype.Timestamptz `json:"applied_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ReviewerID      pgtype.UUID        `json:"reviewer_id"`
	ReviewStatus    string             `json:"review_status"`
	AppliedJobTitle string             `json:"applied_job_title"`
	AssignedAt      pgtype.Timestamp   `json:"assigned_at"`
	RemovedAt       pgtype.Timestamp   `json:"removed_at"`
}

func (q *Queries) ListReviewedCandidates(ctx context.Context, reviewerID pgtype.UUID) ([]ListReviewedCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listReviewedCandidates, reviewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewedCandidatesRow
	for rows.Next() {
		var i ListReviewedCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Avatar,
			&i.Email,
			&i.Phone,
			&i.ExperienceYears,
			&i.Education,
			&i.AppliedJobID,
			&i.Channel,
			&i.ResumeUrl,
			&i.Status,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReviewerID,
			&i.ReviewStatus,
			&i.AppliedJobTitle,
			&i.AssignedAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshToken = `-- name: RefreshToken :one
SELECT id, user_id, device_info, ip_address, user_agent, created_at, expires_at, is_active, last_active_at FROM sessions WHERE id = $1 AND is_active = true AND (expires_at IS NULL OR expires_at > CURRENT_TIMESTAMP) LIMIT 1
`

func (q *Queries) RefreshToken(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, refreshToken, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsActive,
		&i.LastActiveAt,
	)
	return i, err
}

const removeCandidateReviewer = `-- name: RemoveCandidateReviewer :execrows
UPDATE candidate_reviewers
SET removed_at = CURRENT_TIMESTAMP
WHERE candidate_id = $1
  AND removed_at IS NULL
  AND review_status = 'pending'
  AND reviewed_at IS NULL
`

func (q *Queries) RemoveCandidateReviewer(ctx context.Context, candidateID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, removeCandidateReviewer, candidateID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeHRRole = `-- name: RevokeHRRole :exec
UPDATE employees
SET employee_type = 'EMPLOYEE',
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) RevokeHRRole(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeHRRole, id)
	return err
}

const revokeInterviewerRole = `-- name: RevokeInterviewerRole :exec
DELETE FROM recruitment_roles WHERE employee_id = $1 AND role_type = 'INTERVIEWER'
`

func (q *Queries) RevokeInterviewerRole(ctx context.Context, employeeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeInterviewerRole, employeeID)
	return err
}

const revokeRecruiterRole = `-- name: RevokeRecruiterRole :exec
DELETE FROM recruitment_roles WHERE employee_id = $1 AND role_type = 'RECRUITER'
`

func (q *Queries) RevokeRecruiterRole(ctx context.Context, employeeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRecruiterRole, employeeID)
	return err
}

const submitReview = `-- name: SubmitReview :one
UPDATE candidates c
SET review_status = $2,
    updated_at = CURRENT_TIMESTAMP
FROM jobs j
LEFT JOIN employees e ON e.id = (SELECT reviewer_id FROM candidates WHERE id = $1)
WHERE c.id = $1 AND c.applied_job_id = j.id
RETURNING 
    c.id, c.name, c.avatar, c.email, c.phone, c.experience_years, c.education, c.applied_job_id, c.channel, c.resume_url, c.status, c.applied_at, c.created_at, c.updated_at, c.reviewer_id, c.review_status, 
    j.title as applied_job_title,
    e.first_name as reviewer_first_name,
    e.last_name as reviewer_last_name
`

type SubmitReviewParams struct {
	ID           pgtype.UUID `json:"id"`
	ReviewStatus pgtype.Text `json:"review_status"`
}

type SubmitReviewRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Avatar            pgtype.Text        `json:"avatar"`
	Email             string             `json:"email"`
	Phone             string             `json:"phone"`
	ExperienceYears   int32              `json:"experience_years"`
	Education         string             `json:"education"`
	AppliedJobID      pgtype.UUID        `json:"applied_job_id"`
	Channel           string             `json:"channel"`
	ResumeUrl         string             `json:"resume_url"`
	Status            string             `json:"status"`
	AppliedAt         pgtype.Timestamptz `json:"applied_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ReviewerID        pgtype.UUID        `json:"reviewer_id"`
	ReviewStatus      pgtype.Text        `json:"review_status"`
	AppliedJobTitle   string             `json:"applied_job_title"`
	ReviewerFirstName string             `json:"reviewer_first_name"`
	ReviewerLastName  string             `json:"reviewer_last_name"`
}

func (q *Queries) SubmitReview(ctx context.Context, arg SubmitReviewParams) (SubmitReviewRow, error) {
	row := q.db.QueryRow(ctx, submitReview, arg.ID, arg.ReviewStatus)
	var i SubmitReviewRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.ExperienceYears,
		&i.Education,
		&i.AppliedJobID,
		&i.Channel,
		&i.ResumeUrl,
		&i.Status,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewerID,
		&i.ReviewStatus,
		&i.AppliedJobTitle,
		&i.ReviewerFirstName,
		&i.ReviewerLastName,
	)
	return i, err
}

const transferInterview = `-- name: TransferInterview :one
UPDATE interviews
SET interviewer_id = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, candidate_id, interviewer_id, job_id, scheduled_time, status, created_at, updated_at, scheduled_end_time, candidate_status_id, snapshot_status_key, snapshot_status_label
`

type TransferInterviewParams struct {
	ID            pgtype.UUID `json:"id"`
	InterviewerID pgtype.UUID `json:"interviewer_id"`
}

func (q *Queries) TransferInterview(ctx context.Context, arg TransferInterviewParams) (Interview, error) {
	row := q.db.QueryRow(ctx, transferInterview, arg.ID, arg.InterviewerID)
	var i Interview
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.InterviewerID,
		&i.JobID,
		&i.ScheduledTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScheduledEndTime,
		&i.CandidateStatusID,
		&i.SnapshotStatusKey,
		&i.SnapshotStatusLabel,
	)
	return i, err
}

const updateCandidate = `-- name: UpdateCandidate :one
UPDATE candidates
SET name = $2,
    avatar = $3,
    email = $4,
    phone = $5,
    experience_years = $6,
    education = $7,
    applied_job_id = $8,
    channel = $9,
    resume_url = $10,
    status = $11,
    applied_at = $12,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, avatar, email, phone, experience_years, education, applied_job_id, channel, resume_url, status, applied_at, created_at, updated_at, reviewer_id, review_status
`

type UpdateCandidateParams struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Avatar          pgtype.Text        `json:"avatar"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	ExperienceYears int32              `json:"experience_years"`
	Education       string             `json:"education"`
	AppliedJobID    pgtype.UUID        `json:"applied_job_id"`
	Channel         string             `json:"channel"`
	ResumeUrl       string             `json:"resume_url"`
	Status          string             `json:"status"`
	AppliedAt       pgtype.Timestamptz `json:"applied_at"`
}

func (q *Queries) UpdateCandidate(ctx context.Context, arg UpdateCandidateParams) (Candidate, error) {
	row := q.db.QueryRow(ctx, updateCandidate,
		arg.ID,
		arg.Name,
		arg.Avatar,
		arg.Email,
		arg.Phone,
		arg.ExperienceYears,
		arg.Education,
		arg.AppliedJobID,
		arg.Channel,
		arg.ResumeUrl,
		arg.Status,
		arg.AppliedAt,
	)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.ExperienceYears,
		&i.Education,
		&i.AppliedJobID,
		&i.Channel,
		&i.ResumeUrl,
		&i.Status,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewerID,
		&i.ReviewStatus,
	)
	return i, err
}

const updateCandidateResume = `-- name: UpdateCandidateResume :one
UPDATE candidates
SET resume_url = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, avatar, email, phone, experience_years, education, applied_job_id, channel, resume_url, status, applied_at, created_at, updated_at, reviewer_id, review_status
`

type UpdateCandidateResumeParams struct {
	ID        pgtype.UUID `json:"id"`
	ResumeUrl string      `json:"resume_url"`
}

func (q *Queries) UpdateCandidateResume(ctx context.Context, arg UpdateCandidateResumeParams) (Candidate, error) {
	row := q.db.QueryRow(ctx, updateCandidateResume, arg.ID, arg.ResumeUrl)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.ExperienceYears,
		&i.Education,
		&i.AppliedJobID,
		&i.Channel,
		&i.ResumeUrl,
		&i.Status,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewerID,
		&i.ReviewStatus,
	)
	return i, err
}

const updateCandidateReviewerRemovedAt = `-- name: UpdateCandidateReviewerRemovedAt :exec
UPDATE candidate_reviewers
SET removed_at = CURRENT_TIMESTAMP
WHERE candidate_id = $1 AND removed_at IS NULL
`

func (q *Queries) UpdateCandidateReviewerRemovedAt(ctx context.Context, candidateID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateCandidateReviewerRemovedAt, candidateID)
	return err
}

const updateCandidateReviewerReviewStatus = `-- name: UpdateCandidateReviewerReviewStatus :exec
UPDATE candidate_reviewers
SET review_status = $3::varchar,
    reviewed_at = CASE
        WHEN $3::varchar = 'pending' THEN NULL
        ELSE CURRENT_TIMESTAMP
    END
WHERE candidate_id = $1
  AND reviewer_id = $2
  AND removed_at IS NULL
`

type UpdateCandidateReviewerReviewStatusParams struct {
	CandidateID  pgtype.UUID `json:"candidate_id"`
	ReviewerID   pgtype.UUID `json:"reviewer_id"`
	ReviewStatus string      `json:"review_status"`
}

func (q *Queries) UpdateCandidateReviewerReviewStatus(ctx context.Context, arg UpdateCandidateReviewerReviewStatusParams) error {
	_, err := q.db.Exec(ctx, updateCandidateReviewerReviewStatus, arg.CandidateID, arg.ReviewerID, arg.ReviewStatus)
	return err
}

const updateCandidateStatus = `-- name: UpdateCandidateStatus :one
UPDATE candidates
SET status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, avatar, email, phone, experience_years, education, applied_job_id, channel, resume_url, status, applied_at, created_at, updated_at, reviewer_id, review_status
`

type UpdateCandidateStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateCandidateStatus(ctx context.Context, arg UpdateCandidateStatusParams) (Candidate, error) {
	row := q.db.QueryRow(ctx, updateCandidateStatus, arg.ID, arg.Status)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.ExperienceYears,
		&i.Education,
		&i.AppliedJobID,
		&i.Channel,
		&i.ResumeUrl,
		&i.Status,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewerID,
		&i.ReviewStatus,
	)
	return i, err
}

const updateCandidateStatusFields = `-- name: UpdateCandidateStatusFields :one
UPDATE candidate_statuses
SET name = $2,
    color = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, slug, type, sort_order, color, created_at, updated_at, is_deleted
`

type UpdateCandidateStatusFieldsParams struct {
	ID    pgtype.UUID `json:"id"`
	Name  string      `json:"name"`
	Color string      `json:"color"`
}

func (q *Queries) UpdateCandidateStatusFields(ctx context.Context, arg UpdateCandidateStatusFieldsParams) (CandidateStatus, error) {
	row := q.db.QueryRow(ctx, updateCandidateStatusFields, arg.ID, arg.Name, arg.Color)
	var i CandidateStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.SortOrder,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const updateCandidateStatusOrder = `-- name: UpdateCandidateStatusOrder :exec
UPDATE candidate_statuses
SET sort_order = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateCandidateStatusOrderParams struct {
	ID        pgtype.UUID `json:"id"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) UpdateCandidateStatusOrder(ctx context.Context, arg UpdateCandidateStatusOrderParams) error {
	_, err := q.db.Exec(ctx, updateCandidateStatusOrder, arg.ID, arg.SortOrder)
	return err
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees
SET first_name = $2,
    last_name = $3,
    email = $4,
    phone = $5,
    department = $6,
    position = $7,
    status = $8,
    employment_type = $9,
    join_date = $10,
    manager_id = $11,
    user_id = $12,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, first_name, last_name, email, phone, department, position, status, employment_type, join_date, manager_id, user_id, created_at, updated_at, employee_type
`

type UpdateEmployeeParams struct {
	ID             pgtype.UUID        `json:"id"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	Email          string             `json:"email"`
	Phone          string             `json:"phone"`
	Department     string             `json:"department"`
	Position       string             `json:"position"`
	Status         string             `json:"status"`
	EmploymentType string             `json:"employment_type"`
	JoinDate       pgtype.Timestamptz `json:"join_date"`
	ManagerID      pgtype.UUID        `json:"manager_id"`
	UserID         pgtype.UUID        `json:"user_id"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Department,
		arg.Position,
		arg.Status,
		arg.EmploymentType,
		arg.JoinDate,
		arg.ManagerID,
		arg.UserID,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Department,
		&i.Position,
		&i.Status,
		&i.EmploymentType,
		&i.JoinDate,
		&i.ManagerID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmployeeType,
	)
	return i, err
}

const updateInterview = `-- name: UpdateInterview :one
UPDATE interviews
SET scheduled_time = $2,
    scheduled_end_time = $3,
    interviewer_id = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, candidate_id, interviewer_id, job_id, scheduled_time, status, created_at, updated_at, scheduled_end_time, candidate_status_id, snapshot_status_key, snapshot_status_label
`

type UpdateInterviewParams struct {
	ID               pgtype.UUID        `json:"id"`
	ScheduledTime    pgtype.Timestamptz `json:"scheduled_time"`
	ScheduledEndTime pgtype.Timestamptz `json:"scheduled_end_time"`
	InterviewerID    pgtype.UUID        `json:"interviewer_id"`
}

func (q *Queries) UpdateInterview(ctx context.Context, arg UpdateInterviewParams) (Interview, error) {
	row := q.db.QueryRow(ctx, updateInterview,
		arg.ID,
		arg.ScheduledTime,
		arg.ScheduledEndTime,
		arg.InterviewerID,
	)
	var i Interview
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.InterviewerID,
		&i.JobID,
		&i.ScheduledTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScheduledEndTime,
		&i.CandidateStatusID,
		&i.SnapshotStatusKey,
		&i.SnapshotStatusLabel,
	)
	return i, err
}

const updateInterviewStatus = `-- name: UpdateInterviewStatus :one
UPDATE interviews
SET status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, candidate_id, interviewer_id, job_id, scheduled_time, status, created_at, updated_at, scheduled_end_time, candidate_status_id, snapshot_status_key, snapshot_status_label
`

type UpdateInterviewStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateInterviewStatus(ctx context.Context, arg UpdateInterviewStatusParams) (Interview, error) {
	row := q.db.QueryRow(ctx, updateInterviewStatus, arg.ID, arg.Status)
	var i Interview
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.InterviewerID,
		&i.JobID,
		&i.ScheduledTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScheduledEndTime,
		&i.CandidateStatusID,
		&i.SnapshotStatusKey,
		&i.SnapshotStatusLabel,
	)
	return i, err
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET title = $2,
    department = $3,
    head_count = $4,
    open_date = $5,
    job_description = $6,
    note = $7,
    status = $8,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, title, department, head_count, open_date, job_description, note, status, created_at, updated_at
`

type UpdateJobParams struct {
	ID             pgtype.UUID        `json:"id"`
	Title          string             `json:"title"`
	Department     string             `json:"department"`
	HeadCount      int32              `json:"head_count"`
	OpenDate       pgtype.Timestamptz `json:"open_date"`
	JobDescription string             `json:"job_description"`
	Note           pgtype.Text        `json:"note"`
	Status         string             `json:"status"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.ID,
		arg.Title,
		arg.Department,
		arg.HeadCount,
		arg.OpenDate,
		arg.JobDescription,
		arg.Note,
		arg.Status,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Department,
		&i.HeadCount,
		&i.OpenDate,
		&i.JobDescription,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs
SET status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, title, department, head_count, open_date, job_description, note, status, created_at, updated_at
`

type UpdateJobStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus, arg.ID, arg.Status)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Department,
		&i.HeadCount,
		&i.OpenDate,
		&i.JobDescription,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionActivity = `-- name: UpdateSessionActivity :exec
UPDATE sessions 
SET last_active_at = CURRENT_TIMESTAMP 
WHERE id = $1 
AND (last_active_at IS NULL OR last_active_at < (CURRENT_TIMESTAMP - INTERVAL '5 minutes'))
`

func (q *Queries) UpdateSessionActivity(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateSessionActivity, id)
	return err
}

const updateSessionExpiry = `-- name: UpdateSessionExpiry :exec
UPDATE sessions SET expires_at = $2 WHERE id = $1
`

type UpdateSessionExpiryParams struct {
	ID        pgtype.UUID        `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateSessionExpiry(ctx context.Context, arg UpdateSessionExpiryParams) error {
	_, err := q.db.Exec(ctx, updateSessionExpiry, arg.ID, arg.ExpiresAt)
	return err
}
