// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCandidate = `-- name: CreateCandidate :one
INSERT INTO candidates (
  name, avatar, email, phone, experience_years, education, applied_job_id, channel, resume_url, status, note, applied_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, name, avatar, email, phone, experience_years, education, applied_job_id, channel, resume_url, status, note, applied_at, created_at, updated_at
`

type CreateCandidateParams struct {
	Name            string             `json:"name"`
	Avatar          pgtype.Text        `json:"avatar"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	ExperienceYears int32              `json:"experience_years"`
	Education       string             `json:"education"`
	AppliedJobID    pgtype.UUID        `json:"applied_job_id"`
	Channel         string             `json:"channel"`
	ResumeUrl       string             `json:"resume_url"`
	Status          string             `json:"status"`
	Note            pgtype.Text        `json:"note"`
	AppliedAt       pgtype.Timestamptz `json:"applied_at"`
}

func (q *Queries) CreateCandidate(ctx context.Context, arg CreateCandidateParams) (Candidate, error) {
	row := q.db.QueryRow(ctx, createCandidate,
		arg.Name,
		arg.Avatar,
		arg.Email,
		arg.Phone,
		arg.ExperienceYears,
		arg.Education,
		arg.AppliedJobID,
		arg.Channel,
		arg.ResumeUrl,
		arg.Status,
		arg.Note,
		arg.AppliedAt,
	)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.ExperienceYears,
		&i.Education,
		&i.AppliedJobID,
		&i.Channel,
		&i.ResumeUrl,
		&i.Status,
		&i.Note,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
  title, department, head_count, open_date, job_description, note, status
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, title, department, head_count, open_date, job_description, note, status, created_at, updated_at
`

type CreateJobParams struct {
	Title          string             `json:"title"`
	Department     string             `json:"department"`
	HeadCount      int32              `json:"head_count"`
	OpenDate       pgtype.Timestamptz `json:"open_date"`
	JobDescription string             `json:"job_description"`
	Note           pgtype.Text        `json:"note"`
	Status         string             `json:"status"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Title,
		arg.Department,
		arg.HeadCount,
		arg.OpenDate,
		arg.JobDescription,
		arg.Note,
		arg.Status,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Department,
		&i.HeadCount,
		&i.OpenDate,
		&i.JobDescription,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, avatar)
VALUES ($1, $2, $3, $4)
RETURNING id, username, email, password_hash, avatar, created_at, updated_at
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Avatar       pgtype.Text `json:"avatar"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Avatar,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCandidate = `-- name: DeleteCandidate :exec
DELETE FROM candidates
WHERE id = $1
`

func (q *Queries) DeleteCandidate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCandidate, id)
	return err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const getCandidate = `-- name: GetCandidate :one
SELECT c.id, c.name, c.avatar, c.email, c.phone, c.experience_years, c.education, c.applied_job_id, c.channel, c.resume_url, c.status, c.note, c.applied_at, c.created_at, c.updated_at, j.title as applied_job_title
FROM candidates c
JOIN jobs j ON c.applied_job_id = j.id
WHERE c.id = $1 LIMIT 1
`

type GetCandidateRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Avatar          pgtype.Text        `json:"avatar"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	ExperienceYears int32              `json:"experience_years"`
	Education       string             `json:"education"`
	AppliedJobID    pgtype.UUID        `json:"applied_job_id"`
	Channel         string             `json:"channel"`
	ResumeUrl       string             `json:"resume_url"`
	Status          string             `json:"status"`
	Note            pgtype.Text        `json:"note"`
	AppliedAt       pgtype.Timestamptz `json:"applied_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	AppliedJobTitle string             `json:"applied_job_title"`
}

func (q *Queries) GetCandidate(ctx context.Context, id pgtype.UUID) (GetCandidateRow, error) {
	row := q.db.QueryRow(ctx, getCandidate, id)
	var i GetCandidateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.ExperienceYears,
		&i.Education,
		&i.AppliedJobID,
		&i.Channel,
		&i.ResumeUrl,
		&i.Status,
		&i.Note,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppliedJobTitle,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, title, department, head_count, open_date, job_description, note, status, created_at, updated_at FROM jobs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetJob(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Department,
		&i.HeadCount,
		&i.OpenDate,
		&i.JobDescription,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, avatar, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, avatar, created_at, updated_at FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCandidates = `-- name: ListCandidates :many
SELECT c.id, c.name, c.avatar, c.email, c.phone, c.experience_years, c.education, c.applied_job_id, c.channel, c.resume_url, c.status, c.note, c.applied_at, c.created_at, c.updated_at, j.title as applied_job_title
FROM candidates c
JOIN jobs j ON c.applied_job_id = j.id
WHERE ($1::uuid IS NULL OR c.applied_job_id = $1)
ORDER BY c.applied_at DESC
`

type ListCandidatesRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Avatar          pgtype.Text        `json:"avatar"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	ExperienceYears int32              `json:"experience_years"`
	Education       string             `json:"education"`
	AppliedJobID    pgtype.UUID        `json:"applied_job_id"`
	Channel         string             `json:"channel"`
	ResumeUrl       string             `json:"resume_url"`
	Status          string             `json:"status"`
	Note            pgtype.Text        `json:"note"`
	AppliedAt       pgtype.Timestamptz `json:"applied_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	AppliedJobTitle string             `json:"applied_job_title"`
}

func (q *Queries) ListCandidates(ctx context.Context, dollar_1 pgtype.UUID) ([]ListCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listCandidates, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCandidatesRow
	for rows.Next() {
		var i ListCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Avatar,
			&i.Email,
			&i.Phone,
			&i.ExperienceYears,
			&i.Education,
			&i.AppliedJobID,
			&i.Channel,
			&i.ResumeUrl,
			&i.Status,
			&i.Note,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AppliedJobTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, title, department, head_count, open_date, job_description, note, status, created_at, updated_at FROM jobs
ORDER BY created_at DESC
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Department,
			&i.HeadCount,
			&i.OpenDate,
			&i.JobDescription,
			&i.Note,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCandidate = `-- name: UpdateCandidate :one
UPDATE candidates
SET name = $2,
    avatar = $3,
    email = $4,
    phone = $5,
    experience_years = $6,
    education = $7,
    applied_job_id = $8,
    channel = $9,
    resume_url = $10,
    status = $11,
    note = $12,
    applied_at = $13,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, avatar, email, phone, experience_years, education, applied_job_id, channel, resume_url, status, note, applied_at, created_at, updated_at
`

type UpdateCandidateParams struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Avatar          pgtype.Text        `json:"avatar"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	ExperienceYears int32              `json:"experience_years"`
	Education       string             `json:"education"`
	AppliedJobID    pgtype.UUID        `json:"applied_job_id"`
	Channel         string             `json:"channel"`
	ResumeUrl       string             `json:"resume_url"`
	Status          string             `json:"status"`
	Note            pgtype.Text        `json:"note"`
	AppliedAt       pgtype.Timestamptz `json:"applied_at"`
}

func (q *Queries) UpdateCandidate(ctx context.Context, arg UpdateCandidateParams) (Candidate, error) {
	row := q.db.QueryRow(ctx, updateCandidate,
		arg.ID,
		arg.Name,
		arg.Avatar,
		arg.Email,
		arg.Phone,
		arg.ExperienceYears,
		arg.Education,
		arg.AppliedJobID,
		arg.Channel,
		arg.ResumeUrl,
		arg.Status,
		arg.Note,
		arg.AppliedAt,
	)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.ExperienceYears,
		&i.Education,
		&i.AppliedJobID,
		&i.Channel,
		&i.ResumeUrl,
		&i.Status,
		&i.Note,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCandidateNote = `-- name: UpdateCandidateNote :one
UPDATE candidates
SET note = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, avatar, email, phone, experience_years, education, applied_job_id, channel, resume_url, status, note, applied_at, created_at, updated_at
`

type UpdateCandidateNoteParams struct {
	ID   pgtype.UUID `json:"id"`
	Note pgtype.Text `json:"note"`
}

func (q *Queries) UpdateCandidateNote(ctx context.Context, arg UpdateCandidateNoteParams) (Candidate, error) {
	row := q.db.QueryRow(ctx, updateCandidateNote, arg.ID, arg.Note)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.ExperienceYears,
		&i.Education,
		&i.AppliedJobID,
		&i.Channel,
		&i.ResumeUrl,
		&i.Status,
		&i.Note,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCandidateResume = `-- name: UpdateCandidateResume :one
UPDATE candidates
SET resume_url = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, avatar, email, phone, experience_years, education, applied_job_id, channel, resume_url, status, note, applied_at, created_at, updated_at
`

type UpdateCandidateResumeParams struct {
	ID        pgtype.UUID `json:"id"`
	ResumeUrl string      `json:"resume_url"`
}

func (q *Queries) UpdateCandidateResume(ctx context.Context, arg UpdateCandidateResumeParams) (Candidate, error) {
	row := q.db.QueryRow(ctx, updateCandidateResume, arg.ID, arg.ResumeUrl)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.ExperienceYears,
		&i.Education,
		&i.AppliedJobID,
		&i.Channel,
		&i.ResumeUrl,
		&i.Status,
		&i.Note,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCandidateStatus = `-- name: UpdateCandidateStatus :one
UPDATE candidates
SET status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, avatar, email, phone, experience_years, education, applied_job_id, channel, resume_url, status, note, applied_at, created_at, updated_at
`

type UpdateCandidateStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateCandidateStatus(ctx context.Context, arg UpdateCandidateStatusParams) (Candidate, error) {
	row := q.db.QueryRow(ctx, updateCandidateStatus, arg.ID, arg.Status)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.ExperienceYears,
		&i.Education,
		&i.AppliedJobID,
		&i.Channel,
		&i.ResumeUrl,
		&i.Status,
		&i.Note,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET title = $2,
    department = $3,
    head_count = $4,
    open_date = $5,
    job_description = $6,
    note = $7,
    status = $8,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, title, department, head_count, open_date, job_description, note, status, created_at, updated_at
`

type UpdateJobParams struct {
	ID             pgtype.UUID        `json:"id"`
	Title          string             `json:"title"`
	Department     string             `json:"department"`
	HeadCount      int32              `json:"head_count"`
	OpenDate       pgtype.Timestamptz `json:"open_date"`
	JobDescription string             `json:"job_description"`
	Note           pgtype.Text        `json:"note"`
	Status         string             `json:"status"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.ID,
		arg.Title,
		arg.Department,
		arg.HeadCount,
		arg.OpenDate,
		arg.JobDescription,
		arg.Note,
		arg.Status,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Department,
		&i.HeadCount,
		&i.OpenDate,
		&i.JobDescription,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs
SET status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, title, department, head_count, open_date, job_description, note, status, created_at, updated_at
`

type UpdateJobStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus, arg.ID, arg.Status)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Department,
		&i.HeadCount,
		&i.OpenDate,
		&i.JobDescription,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

// ============ Employee Queries ============

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (
  first_name, last_name, email, phone, department, position, status, employment_type, join_date, manager_id, user_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, first_name, last_name, email, phone, department, position, status, employment_type, join_date, manager_id, user_id, created_at, updated_at
`

type CreateEmployeeParams struct {
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	Email          string             `json:"email"`
	Phone          string             `json:"phone"`
	Department     string             `json:"department"`
	Position       string             `json:"position"`
	Status         string             `json:"status"`
	EmploymentType string             `json:"employment_type"`
	JoinDate       pgtype.Timestamptz `json:"join_date"`
	ManagerID      pgtype.UUID        `json:"manager_id"`
	UserID         pgtype.UUID        `json:"user_id"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Department,
		arg.Position,
		arg.Status,
		arg.EmploymentType,
		arg.JoinDate,
		arg.ManagerID,
		arg.UserID,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Department,
		&i.Position,
		&i.Status,
		&i.EmploymentType,
		&i.JoinDate,
		&i.ManagerID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployee = `-- name: GetEmployee :one
SELECT id, first_name, last_name, email, phone, department, position, status, employment_type, join_date, manager_id, user_id, created_at, updated_at FROM employees
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEmployee(ctx context.Context, id pgtype.UUID) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployee, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Department,
		&i.Position,
		&i.Status,
		&i.EmploymentType,
		&i.JoinDate,
		&i.ManagerID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmployees = `-- name: ListEmployees :many
SELECT id, first_name, last_name, email, phone, department, position, status, employment_type, join_date, manager_id, user_id, created_at, updated_at FROM employees
WHERE ($1::varchar IS NULL OR $1 = '' OR status = $1)
  AND ($2::varchar IS NULL OR $2 = '' OR department = $2)
  AND ($3::varchar IS NULL OR $3 = '' OR first_name ILIKE '%' || $3 || '%' OR last_name ILIKE '%' || $3 || '%' OR email ILIKE '%' || $3 || '%')
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListEmployeesParams struct {
	Status     pgtype.Text `json:"status"`
	Department pgtype.Text `json:"department"`
	Search     pgtype.Text `json:"search"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployees,
		arg.Status,
		arg.Department,
		arg.Search,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Department,
			&i.Position,
			&i.Status,
			&i.EmploymentType,
			&i.JoinDate,
			&i.ManagerID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countEmployees = `-- name: CountEmployees :one
SELECT COUNT(*) FROM employees
WHERE ($1::varchar IS NULL OR $1 = '' OR status = $1)
  AND ($2::varchar IS NULL OR $2 = '' OR department = $2)
  AND ($3::varchar IS NULL OR $3 = '' OR first_name ILIKE '%' || $3 || '%' OR last_name ILIKE '%' || $3 || '%' OR email ILIKE '%' || $3 || '%')
`

type CountEmployeesParams struct {
	Status     pgtype.Text `json:"status"`
	Department pgtype.Text `json:"department"`
	Search     pgtype.Text `json:"search"`
}

func (q *Queries) CountEmployees(ctx context.Context, arg CountEmployeesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployees,
		arg.Status,
		arg.Department,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees
SET first_name = $2,
    last_name = $3,
    email = $4,
    phone = $5,
    department = $6,
    position = $7,
    status = $8,
    employment_type = $9,
    join_date = $10,
    manager_id = $11,
    user_id = $12,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, first_name, last_name, email, phone, department, position, status, employment_type, join_date, manager_id, user_id, created_at, updated_at
`

type UpdateEmployeeParams struct {
	ID             pgtype.UUID        `json:"id"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	Email          string             `json:"email"`
	Phone          string             `json:"phone"`
	Department     string             `json:"department"`
	Position       string             `json:"position"`
	Status         string             `json:"status"`
	EmploymentType string             `json:"employment_type"`
	JoinDate       pgtype.Timestamptz `json:"join_date"`
	ManagerID      pgtype.UUID        `json:"manager_id"`
	UserID         pgtype.UUID        `json:"user_id"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Department,
		arg.Position,
		arg.Status,
		arg.EmploymentType,
		arg.JoinDate,
		arg.ManagerID,
		arg.UserID,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Department,
		&i.Position,
		&i.Status,
		&i.EmploymentType,
		&i.JoinDate,
		&i.ManagerID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEmployee = `-- name: DeleteEmployee :exec
DELETE FROM employees
WHERE id = $1
`

func (q *Queries) DeleteEmployee(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmployee, id)
	return err
}
