// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCandidate = `-- name: CreateCandidate :one
INSERT INTO candidates (
  name, avatar, email, phone, experience_years, education, applied_job_id, channel, resume_url, status, note, applied_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, name, avatar, email, phone, experience_years, education, applied_job_id, channel, resume_url, status, note, applied_at, created_at, updated_at
`

type CreateCandidateParams struct {
	Name            string             `json:"name"`
	Avatar          pgtype.Text        `json:"avatar"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	ExperienceYears int32              `json:"experience_years"`
	Education       string             `json:"education"`
	AppliedJobID    pgtype.UUID        `json:"applied_job_id"`
	Channel         string             `json:"channel"`
	ResumeUrl       string             `json:"resume_url"`
	Status          string             `json:"status"`
	Note            pgtype.Text        `json:"note"`
	AppliedAt       pgtype.Timestamptz `json:"applied_at"`
}

func (q *Queries) CreateCandidate(ctx context.Context, arg CreateCandidateParams) (Candidate, error) {
	row := q.db.QueryRow(ctx, createCandidate,
		arg.Name,
		arg.Avatar,
		arg.Email,
		arg.Phone,
		arg.ExperienceYears,
		arg.Education,
		arg.AppliedJobID,
		arg.Channel,
		arg.ResumeUrl,
		arg.Status,
		arg.Note,
		arg.AppliedAt,
	)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.ExperienceYears,
		&i.Education,
		&i.AppliedJobID,
		&i.Channel,
		&i.ResumeUrl,
		&i.Status,
		&i.Note,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
  title, department, head_count, open_date, job_description, note, status
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, title, department, head_count, open_date, job_description, note, status, created_at, updated_at
`

type CreateJobParams struct {
	Title          string             `json:"title"`
	Department     string             `json:"department"`
	HeadCount      int32              `json:"head_count"`
	OpenDate       pgtype.Timestamptz `json:"open_date"`
	JobDescription string             `json:"job_description"`
	Note           pgtype.Text        `json:"note"`
	Status         string             `json:"status"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Title,
		arg.Department,
		arg.HeadCount,
		arg.OpenDate,
		arg.JobDescription,
		arg.Note,
		arg.Status,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Department,
		&i.HeadCount,
		&i.OpenDate,
		&i.JobDescription,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCandidate = `-- name: DeleteCandidate :exec
DELETE FROM candidates
WHERE id = $1
`

func (q *Queries) DeleteCandidate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCandidate, id)
	return err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const getCandidate = `-- name: GetCandidate :one
SELECT c.id, c.name, c.avatar, c.email, c.phone, c.experience_years, c.education, c.applied_job_id, c.channel, c.resume_url, c.status, c.note, c.applied_at, c.created_at, c.updated_at, j.title as applied_job_title
FROM candidates c
JOIN jobs j ON c.applied_job_id = j.id
WHERE c.id = $1 LIMIT 1
`

type GetCandidateRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Avatar          pgtype.Text        `json:"avatar"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	ExperienceYears int32              `json:"experience_years"`
	Education       string             `json:"education"`
	AppliedJobID    pgtype.UUID        `json:"applied_job_id"`
	Channel         string             `json:"channel"`
	ResumeUrl       string             `json:"resume_url"`
	Status          string             `json:"status"`
	Note            pgtype.Text        `json:"note"`
	AppliedAt       pgtype.Timestamptz `json:"applied_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	AppliedJobTitle string             `json:"applied_job_title"`
}

func (q *Queries) GetCandidate(ctx context.Context, id pgtype.UUID) (GetCandidateRow, error) {
	row := q.db.QueryRow(ctx, getCandidate, id)
	var i GetCandidateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.ExperienceYears,
		&i.Education,
		&i.AppliedJobID,
		&i.Channel,
		&i.ResumeUrl,
		&i.Status,
		&i.Note,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppliedJobTitle,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, title, department, head_count, open_date, job_description, note, status, created_at, updated_at FROM jobs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetJob(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Department,
		&i.HeadCount,
		&i.OpenDate,
		&i.JobDescription,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCandidates = `-- name: ListCandidates :many
SELECT c.id, c.name, c.avatar, c.email, c.phone, c.experience_years, c.education, c.applied_job_id, c.channel, c.resume_url, c.status, c.note, c.applied_at, c.created_at, c.updated_at, j.title as applied_job_title
FROM candidates c
JOIN jobs j ON c.applied_job_id = j.id
WHERE ($1::uuid IS NULL OR c.applied_job_id = $1)
ORDER BY c.applied_at DESC
`

type ListCandidatesRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Avatar          pgtype.Text        `json:"avatar"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	ExperienceYears int32              `json:"experience_years"`
	Education       string             `json:"education"`
	AppliedJobID    pgtype.UUID        `json:"applied_job_id"`
	Channel         string             `json:"channel"`
	ResumeUrl       string             `json:"resume_url"`
	Status          string             `json:"status"`
	Note            pgtype.Text        `json:"note"`
	AppliedAt       pgtype.Timestamptz `json:"applied_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	AppliedJobTitle string             `json:"applied_job_title"`
}

func (q *Queries) ListCandidates(ctx context.Context, dollar_1 pgtype.UUID) ([]ListCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listCandidates, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCandidatesRow
	for rows.Next() {
		var i ListCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Avatar,
			&i.Email,
			&i.Phone,
			&i.ExperienceYears,
			&i.Education,
			&i.AppliedJobID,
			&i.Channel,
			&i.ResumeUrl,
			&i.Status,
			&i.Note,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AppliedJobTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, title, department, head_count, open_date, job_description, note, status, created_at, updated_at FROM jobs
ORDER BY created_at DESC
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Department,
			&i.HeadCount,
			&i.OpenDate,
			&i.JobDescription,
			&i.Note,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCandidate = `-- name: UpdateCandidate :one
UPDATE candidates
SET name = $2,
    avatar = $3,
    email = $4,
    phone = $5,
    experience_years = $6,
    education = $7,
    applied_job_id = $8,
    channel = $9,
    resume_url = $10,
    status = $11,
    note = $12,
    applied_at = $13,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, avatar, email, phone, experience_years, education, applied_job_id, channel, resume_url, status, note, applied_at, created_at, updated_at
`

type UpdateCandidateParams struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Avatar          pgtype.Text        `json:"avatar"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	ExperienceYears int32              `json:"experience_years"`
	Education       string             `json:"education"`
	AppliedJobID    pgtype.UUID        `json:"applied_job_id"`
	Channel         string             `json:"channel"`
	ResumeUrl       string             `json:"resume_url"`
	Status          string             `json:"status"`
	Note            pgtype.Text        `json:"note"`
	AppliedAt       pgtype.Timestamptz `json:"applied_at"`
}

func (q *Queries) UpdateCandidate(ctx context.Context, arg UpdateCandidateParams) (Candidate, error) {
	row := q.db.QueryRow(ctx, updateCandidate,
		arg.ID,
		arg.Name,
		arg.Avatar,
		arg.Email,
		arg.Phone,
		arg.ExperienceYears,
		arg.Education,
		arg.AppliedJobID,
		arg.Channel,
		arg.ResumeUrl,
		arg.Status,
		arg.Note,
		arg.AppliedAt,
	)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.ExperienceYears,
		&i.Education,
		&i.AppliedJobID,
		&i.Channel,
		&i.ResumeUrl,
		&i.Status,
		&i.Note,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCandidateNote = `-- name: UpdateCandidateNote :one
UPDATE candidates
SET note = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, avatar, email, phone, experience_years, education, applied_job_id, channel, resume_url, status, note, applied_at, created_at, updated_at
`

type UpdateCandidateNoteParams struct {
	ID   pgtype.UUID `json:"id"`
	Note pgtype.Text `json:"note"`
}

func (q *Queries) UpdateCandidateNote(ctx context.Context, arg UpdateCandidateNoteParams) (Candidate, error) {
	row := q.db.QueryRow(ctx, updateCandidateNote, arg.ID, arg.Note)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.ExperienceYears,
		&i.Education,
		&i.AppliedJobID,
		&i.Channel,
		&i.ResumeUrl,
		&i.Status,
		&i.Note,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCandidateResume = `-- name: UpdateCandidateResume :one
UPDATE candidates
SET resume_url = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, avatar, email, phone, experience_years, education, applied_job_id, channel, resume_url, status, note, applied_at, created_at, updated_at
`

type UpdateCandidateResumeParams struct {
	ID        pgtype.UUID `json:"id"`
	ResumeUrl string      `json:"resume_url"`
}

func (q *Queries) UpdateCandidateResume(ctx context.Context, arg UpdateCandidateResumeParams) (Candidate, error) {
	row := q.db.QueryRow(ctx, updateCandidateResume, arg.ID, arg.ResumeUrl)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.ExperienceYears,
		&i.Education,
		&i.AppliedJobID,
		&i.Channel,
		&i.ResumeUrl,
		&i.Status,
		&i.Note,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCandidateStatus = `-- name: UpdateCandidateStatus :one
UPDATE candidates
SET status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, avatar, email, phone, experience_years, education, applied_job_id, channel, resume_url, status, note, applied_at, created_at, updated_at
`

type UpdateCandidateStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateCandidateStatus(ctx context.Context, arg UpdateCandidateStatusParams) (Candidate, error) {
	row := q.db.QueryRow(ctx, updateCandidateStatus, arg.ID, arg.Status)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.ExperienceYears,
		&i.Education,
		&i.AppliedJobID,
		&i.Channel,
		&i.ResumeUrl,
		&i.Status,
		&i.Note,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET title = $2,
    department = $3,
    head_count = $4,
    open_date = $5,
    job_description = $6,
    note = $7,
    status = $8,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, title, department, head_count, open_date, job_description, note, status, created_at, updated_at
`

type UpdateJobParams struct {
	ID             pgtype.UUID        `json:"id"`
	Title          string             `json:"title"`
	Department     string             `json:"department"`
	HeadCount      int32              `json:"head_count"`
	OpenDate       pgtype.Timestamptz `json:"open_date"`
	JobDescription string             `json:"job_description"`
	Note           pgtype.Text        `json:"note"`
	Status         string             `json:"status"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.ID,
		arg.Title,
		arg.Department,
		arg.HeadCount,
		arg.OpenDate,
		arg.JobDescription,
		arg.Note,
		arg.Status,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Department,
		&i.HeadCount,
		&i.OpenDate,
		&i.JobDescription,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs
SET status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, title, department, head_count, open_date, job_description, note, status, created_at, updated_at
`

type UpdateJobStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus, arg.ID, arg.Status)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Department,
		&i.HeadCount,
		&i.OpenDate,
		&i.JobDescription,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
