// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCandidate(ctx context.Context, arg CreateCandidateParams) (Candidate, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCandidate(ctx context.Context, id pgtype.UUID) error
	DeleteJob(ctx context.Context, id pgtype.UUID) error
	GetCandidate(ctx context.Context, id pgtype.UUID) (GetCandidateRow, error)
	GetJob(ctx context.Context, id pgtype.UUID) (Job, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListCandidates(ctx context.Context, dollar_1 pgtype.UUID) ([]ListCandidatesRow, error)
	ListJobs(ctx context.Context) ([]Job, error)
	UpdateCandidate(ctx context.Context, arg UpdateCandidateParams) (Candidate, error)
	UpdateCandidateNote(ctx context.Context, arg UpdateCandidateNoteParams) (Candidate, error)
	UpdateCandidateResume(ctx context.Context, arg UpdateCandidateResumeParams) (Candidate, error)
	UpdateCandidateStatus(ctx context.Context, arg UpdateCandidateStatusParams) (Candidate, error)
	UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error)
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error)
	// Employee methods
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error)
	GetEmployee(ctx context.Context, id pgtype.UUID) (Employee, error)
	ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]Employee, error)
	CountEmployees(ctx context.Context, arg CountEmployeesParams) (int64, error)
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error)
	DeleteEmployee(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
